infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          ['.github/**/*', 'docker-compose.yml', 'parsers.dockerfile', '.dockerignore']

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          [
            'poetry.lock',
            'pyproject.toml',
            'mobileapp/package.json',
            'mobileapp/pnpm-lock.yaml',
            'mockserver/package.json',
            'mockserver/pnpm-lock.yaml',
            'web/package.json',
            'web/pnpm-lock.yaml',
          ]

frontend 🎨:
  - all:
      - changed-files:
          - any-glob-to-any-file: 'web/**/*'
          - all-globs-to-all-files: '!web/public/locales/**/*'

translations 🗣:
  - changed-files:
      - any-glob-to-any-file: 'web/public/locales/**/*'

tests:
  - changed-files:
      - any-glob-to-any-file: ['tests/**/*', 'parsers/test/**/*']

javascript:
  - changed-files:
      - any-glob-to-any-file: '**/*.js'

python:
  - changed-files:
      - any-glob-to-any-file: '**/*.py'

parser:
  - all:
      - changed-files:
          - any-glob-to-any-file: 'parsers/**/*'
          - all-globs-to-all-files: '!parsers/archive/**/*'

archived parser:
  - changed-files:
      - any-glob-to-any-file: 'parsers/archive/**/*'

capacity parser:
  - changed-files:
      - any-glob-to-any-file: 'electricitymap/contrib/capacity_parsers/**/*'

mobile app 📱:
  - changed-files:
      - any-glob-to-any-file: 'mobileapp/**/*'

exchange config:
  - changed-files:
      - any-glob-to-any-file: 'config/exchanges/**/*.yaml'

zone config:
  - changed-files:
      - any-glob-to-any-file: 'config/zones/**/*.yaml'
