bounding_box:
  - - 9.47996951665
    - 46.4318173285
  - - 16.9796667823
    - 49.0390742051
capacity:
  biomass:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 585.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 584.0
  coal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 0.0
  gas:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 4206.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 4225.0
  geothermal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 0.0
  hydro:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 8673.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 8336.0
  hydro storage:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 3363.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 3485.0
  nuclear:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 0.0
  oil:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 120.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 122.0
  solar:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 3265.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 6305.0
  unknown:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 845.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 879.0
  wind:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 3569.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 3967.0
contributors:
  - corradio
  - brandongalbraith
country: AT
delays:
  production: 6
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 288.40156041028825
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 300.03226072692223
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 297.08368558857046
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 269.7227523806142
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 226.48197661515908
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 185.90872608172538
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 237.14249712142382
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 1057.262766
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1075.5
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 435.2364657
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 407.84
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 380.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 288.40156041028825
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 300.03226072692223
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 297.08368558857046
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 269.7227523806142
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 226.48197661515908
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 185.90872608172538
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 237.14249712142382
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 641.08
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 344.43
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 284.3
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 281.43
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 253.88
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 211.99
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 171.79
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 223.86
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 233.29
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 136.69
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1168.890109
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1187.127343
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 555.2364657
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 527.8399999999999
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 500.0
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 344.43
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 284.3
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 281.43
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 253.88
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 211.99
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 171.79
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 223.86
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 233.29
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 136.69
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 885.08
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 31.0
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.051071595089056086
        coal: 0.17508933729535006
        gas: 0.1210720713860492
        geothermal: 4.018738745707861e-05
        hydro: 0.2950083756952926
        hydro discharge: 0.059354295377081825
        nuclear: 0.07894175622136311
        oil: 0.0008278344955549013
        solar: 0.027521929090297628
        unknown: 0.09614889594776513
        wind: 0.09492380791184424
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.058046406194726965
        coal: 0.14321001485471613
        gas: 0.11704915948819578
        geothermal: 4.9624356963156514e-05
        hydro: 0.4133036730434246
        hydro discharge: 0.069024690725902
        nuclear: 0.06212226986933998
        oil: 0.0007253083264983775
        solar: 0.02573745866354416
        unknown: 0.018792759839384186
        wind: 0.09193873606209844
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.05821344022977672
        coal: 0.1384271174620504
        gas: 0.135805194494946
        geothermal: 5.411323500733893e-05
        hydro: 0.37363138177532657
        hydro discharge: 0.06074029504882421
        nuclear: 0.06382561386185179
        oil: 0.0008126547211688449
        solar: 0.02974828894390436
        unknown: 0.02130134914714325
        wind: 0.11744053848604519
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.059881266786736
        coal: 0.13462199722581453
        gas: 0.12454374799030027
        geothermal: 5.3302664658443456e-05
        hydro: 0.3837275232580418
        hydro discharge: 0.06499358869135742
        nuclear: 0.07033603743755869
        oil: 0.00096832118168371
        solar: 0.03556425718188646
        unknown: 0.010527732272316164
        wind: 0.11478221729167852
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.05268090346730125
        coal: 0.10063171767401037
        gas: 0.14695227417054021
        geothermal: 5.0172289321607884e-05
        hydro: 0.39872859284584744
        hydro discharge: 0.05992529310268704
        nuclear: 0.06151256576590478
        oil: 0.0012347091580984493
        solar: 0.03284447611015338
        unknown: 0.009108229198011382
        wind: 0.1363310407473548
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.048194412937729345
        coal: 0.07079424878111862
        gas: 0.1382652448396477
        geothermal: 5.7694277798706334e-05
        hydro: 0.4341795049593528
        hydro discharge: 0.0792686352909074
        nuclear: 0.05699807843529942
        oil: 0.0011669258836047587
        solar: 0.02892971506420771
        unknown: 0.009447431494279734
        wind: 0.13269806931272968
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.044776905235904274
        coal: 0.08842234289995128
        gas: 0.14951292307986597
        geothermal: 4.383133523764864e-05
        hydro: 0.4169315127692896
        hydro discharge: 0.0746864237317435
        nuclear: 0.06560267343151828
        oil: 0.0008848024970060967
        solar: 0.028044103032220262
        unknown: 0.009583700250242548
        wind: 0.12151076520307155
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03571047043133149
        coal: 0.10786121389112523
        gas: 0.1593492533168509
        geothermal: 4.918394244206113e-05
        hydro: 0.38413043691329246
        hydro discharge: 0.07627261366622375
        nuclear: 0.06780244174146945
        oil: 0.0009097117290625757
        solar: 0.029599570946268184
        unknown: 0.008589010023244763
        wind: 0.12972605708951385
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 5.166911013275682e-10
        biomass: 0.041534532289704613
        coal: 0.06744996208625759
        gas: 0.10291921857287113
        geothermal: 3.748042802956758e-05
        hydro: 0.4653292944329385
        hydro discharge: 0.07455539322342075
        nuclear: 0.053021452469245785
        oil: 0.000683081308918452
        solar: 0.04735309308659243
        unknown: 0.0055008934241895045
        wind: 0.14161554511418753
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: NORDPOOL.fetch_price
  production: ENTSOE.fetch_production
  productionCapacity: ENTSOE.fetch_production_capacity
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Vienna
