bounding_box:
  - - 128.50011600215169
    - -38.57057057099979
  - - 141.50010704970066
    - -25.499911390797962
capacity:
  battery storage:
    - datetime: '2023-01-01'
      source: opennem.org.au
      value: 716.27
    - datetime: '2021-01-01'
      source: opennem.org.au
      value: 416.27
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 410.0
  biomass:
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 10.0
  gas:
    - datetime: '2023-01-01'
      source: opennem.org.au
      value: 3228.0
    - datetime: '2022-01-01'
      source: opennem.org.au
      value: 3100.0
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 2946.0
  oil:
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 456.6
  solar:
    - datetime: '2023-01-01'
      source: opennem.org.au
      value: 2900.52
    - datetime: '2022-01-01'
      source: opennem.org.au
      value: 2785.05
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 2686.05
  wind:
    - datetime: '2023-01-01'
      source: opennem.org.au
      value: 2763.4
    - datetime: '2022-01-01'
      source: opennem.org.au
      value: 2350.9
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 2140.9
contributors:
  - brandongalbraith
  - jarek
  - corradio
country: AU
delays:
  production: 5
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 195.34605602031309
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 195.35045278669472
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 244.8445316787786
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 253.4048988280059
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 260.323058651702
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 206.45227689976784
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 210.20870605862984
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 195.34605602031309
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 195.35045278669472
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 244.8445316787786
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 253.4048988280059
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 260.323058651702
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 206.45227689976784
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 210.20870605862984
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 195.34605602031309
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 195.35045278669472
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 168.38
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 222.04
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 243.79
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 202.54
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 183.41
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 142.62
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 129.81
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 195.34605602031309
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 195.35045278669472
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 168.38
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 222.04
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 243.79
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 202.54
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 183.41
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 142.62
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 129.81
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0012441841875993629
        biomass: 0.0
        coal: 0.0
        gas: 0.44392266438796935
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.001647547198720754
        solar: 0.0921279565822379
        unknown: 0.0
        wind: 0.46105750198504725
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.001244153785664184
        biomass: 0.0
        coal: 2.269165430313992e-05
        gas: 0.44391182571640486
        geothermal: 0.0
        hydro: 1.2631034958608364e-07
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0016475069405149038
        solar: 0.09212688257652056
        unknown: 0.0
        wind: 0.46104666775934067
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0017806901988653345
        biomass: 0.0
        coal: 0.0
        gas: 0.39057890837387454
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0013338032490859085
        solar: 0.14332000313959103
        unknown: 0.0
        wind: 0.4629860235718955
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0022371866977428955
        biomass: 0.0
        coal: 0.0
        gas: 0.47308523386620427
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0010414766509621277
        solar: 0.09947681417648245
        unknown: 0.0
        wind: 0.4241594895967854
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0030727559146749876
        biomass: 0.0
        coal: 0.0
        gas: 0.5313695468883676
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0006985699892859676
        solar: 0.04662866046543386
        unknown: 0.0
        wind: 0.41823080049343486
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.004393504897215077
        biomass: 0.0
        coal: 0.0
        gas: 0.4617797670617228
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0005690649271097908
        solar: 0.06428898198017026
        unknown: 0.0
        wind: 0.4689687692415629
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0071610083528132985
        biomass: 0.0
        coal: 0.0
        gas: 0.3857915493889897
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.001319332702641473
        solar: 0.10396008088043397
        unknown: 0.0
        wind: 0.5017679182547047
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.004961337333845281
        biomass: 0.0
        coal: 0.0
        gas: 0.30836762614484114
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.004476128276825672
        solar: 0.17414425567189298
        unknown: 0.0
        wind: 0.5080506175945515
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.005477724338481898
        biomass: 1.1860213093110744e-06
        coal: 0.06989598237598818
        gas: 0.22238498893360797
        geothermal: 0.0
        hydro: 0.01025399983491562
        hydro discharge: 1.4393462491639252e-09
        nuclear: 0.0
        oil: 0.0009492042315898845
        solar: 0.2472717562478757
        unknown: 0.0
        wind: 0.44376506229970586
parsers:
  price: OPENNEM.fetch_price
  production: OPENNEM.fetch_production
  productionCapacity: OPENNEM.fetch_production_capacity
region: Oceania
timezone: Australia/Adelaide
