bounding_box:
  - - 143.33716881600026
    - -44.1412899719998
  - - 148.98454837300017
    - -39.07146575299984
capacity:
  biomass:
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 2.0
  gas:
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 371.6
  hydro:
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 2361.0
  oil:
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 48.0
  solar:
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 303.37
  wind:
    - datetime: '2020-01-01'
      source: opennem.org.au
      value: 567.0
contributors:
  - brandongalbraith
  - jarek
  - corradio
country: AU
delays:
  production: 5
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 24.911345119619092
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 24.93317917581306
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 100.44014991218829
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 58.81330851188387
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 80.95101409049424
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 30.104873967039712
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 60.40527046772535
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 24.911345119619092
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 24.93317917581306
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 100.44014991218829
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 58.81330851188387
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 80.95101409049424
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 30.104873967039712
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 60.40527046772535
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 24.911345119619092
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 24.93317917581306
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 25.06
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 25.06
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 25.06
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 25.25
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 22.88
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 21.35
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 25.49
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 24.911345119619092
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 24.93317917581306
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 25.06
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 25.06
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 25.06
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 25.25
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 22.88
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 21.35
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 25.49
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.006251202386553182
        geothermal: 0.0
        hydro: 0.8220362701091669
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.017750273698283935
        unknown: 0.0
        wind: 0.1539614486793389
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 4.209137046354714e-05
        gas: 0.006250930266152664
        geothermal: 0.0
        hydro: 0.8220004964594964
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.017750193803841564
        unknown: 0.0
        wind: 0.15395548250199584
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.006618208559564372
        geothermal: 0.0
        hydro: 0.8041733429393989
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.024818268671036193
        unknown: 0.0
        wind: 0.16438968042754365
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.006618208559564372
        geothermal: 0.0
        hydro: 0.8041733429393989
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.024818268671036193
        unknown: 0.0
        wind: 0.16438968042754365
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.006616413805282455
        geothermal: 0.0
        hydro: 0.8041348118410394
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.024835632370595145
        unknown: 0.0
        wind: 0.16441264327450741
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.007786527357218331
        geothermal: 0.0
        hydro: 0.8161354912451999
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.018408789547668468
        unknown: 0.0
        wind: 0.15766922656069593
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.001861257519089156
        geothermal: 0.0
        hydro: 0.8265758030327586
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.006728512818955391
        unknown: 0.0
        wind: 0.16483446246331912
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.009606228124582174
        geothermal: 0.0
        hydro: 0.8175407688585076
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.018977767022211215
        unknown: 0.0
        wind: 0.153875257658378
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.00014181051801296526
        biomass: 2.7825846875018085e-06
        coal: 0.07853787602759113
        gas: 0.005549875654376148
        geothermal: 0.0
        hydro: 0.6648362872048628
        hydro discharge: 2.4640795855214438e-08
        nuclear: 0.0
        oil: 1.0714183086674723e-06
        solar: 0.05785319462656997
        unknown: 0.0
        wind: 0.19307706728595234
parsers:
  price: OPENNEM.fetch_price
  production: OPENNEM.fetch_production
  productionCapacity: OPENNEM.fetch_production_capacity
region: Oceania
timezone: Australia/Hobart
