bounding_box:
  - - 19.013194207000083
    - 59.40448639500012
  - - 21.59669030000012
    - 60.98078034100014
capacity:
  coal: 0
  gas: 0
  nuclear: 0
  oil: 35
  solar: 3.67
  wind: 63.8
contributors:
  - tmslaine
  - systemcatch
  - VIKTORVAV99
country: AX
delays:
  production: 5
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 20.526087757405882
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 12.530239974673977
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 7.94010936501788
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 13.59160327602624
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 895.6862569
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1075.5
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 295.9885661
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 412.38
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 20.526087757405882
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 12.530239974673977
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 7.94010936501788
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 13.59160327602624
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 641.08
  lifecycle:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 98.82
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 49.18
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 32.88
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 27.6
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 38.57
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 26.65
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 22.15
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 990.5340999
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1170.347843
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 415.9885661
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 532.38
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 98.82
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 49.18
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 32.88
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 27.6
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 38.57
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 26.65
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 22.15
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 885.08
    wind:
      datetime: '2020-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.3916076049049387
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0009224884688941389
        solar: 0.0
        unknown: 0.0
        wind: 0.6073799077511531
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.050316256338338784
        coal: 0.01190021334890858
        gas: 0.005878057758726469
        geothermal: 0.0
        hydro: 0.2401629548979274
        hydro discharge: 1.6128716668004633e-05
        nuclear: 0.33528716338847153
        oil: 0.0009197025806129534
        solar: 0.004118125843123178
        unknown: 0.04398725282787423
        wind: 0.307375925458265
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.007356650926366126
        coal: 0.007171752521309687
        gas: 0.004433729796902853
        geothermal: 0.0
        hydro: 0.2545246011481863
        hydro discharge: 1.2655011004385396e-05
        nuclear: 0.3513904991200742
        oil: 0.0002768967929432825
        solar: 0.004285347377797997
        unknown: 0.04460440564404474
        wind: 0.3259211785376681
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.004021778114159461
        coal: 0.004385242704692326
        gas: 0.0034162843515868806
        geothermal: 0.0
        hydro: 0.30334678639361756
        hydro discharge: 0.001028716564312915
        nuclear: 0.30980107720319855
        oil: 0.00023095286134266902
        solar: 0.004101298618312724
        unknown: 0.039300501016209424
        wind: 0.3303431558887037
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0068600874365692555
        coal: 0.0064758503565906025
        gas: 0.003931807657593519
        geothermal: 0.0
        hydro: 0.2633747501582596
        hydro discharge: 0.0011307940276785431
        nuclear: 0.326887539125958
        oil: 0.0018800944372743557
        solar: 0.00036411835940856684
        unknown: 0.06393762928373665
        wind: 0.3251014539829839
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.004674754849715956
        coal: 0.00503813110886851
        gas: 0.0015282126016185839
        geothermal: 0.0
        hydro: 0.23736799532594713
        hydro discharge: 0.00022890264213749342
        nuclear: 0.24147671084418582
        oil: 9.215604327877765e-05
        solar: 0.0025385196049196555
        unknown: 0.036478717920579946
        wind: 0.4705321441582579
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0034986139814784296
        coal: 0.003730375209994895
        gas: 0.0015950355024430861
        geothermal: 0.0
        hydro: 0.20538788393927254
        hydro discharge: 0.00025462937478523505
        nuclear: 0.2028770251982546
        oil: 8.609184477654547e-05
        solar: 0.0038977091533578595
        unknown: 0.02464779072290281
        wind: 0.553986365699678
parsers:
  consumption: AX.fetch_consumption
  price: ENTSOE.fetch_price
  production: AX.fetch_production
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Mariehamn
