bounding_box:
  - - 22.3805257504
    - 41.2344859889
  - - 28.5580814959
    - 44.2349230007
capacity:
  biomass:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 80.0
  coal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 4469.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 4475.0
  gas:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1322.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 699.0
  geothermal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 0.0
  hydro:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 2350.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 2352.0
  hydro storage:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 864.0
  nuclear:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 2080.0
  oil:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 0.0
  solar:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 2879.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 3179.0
  unknown:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 0.0
  wind:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 705.0
contributors:
  - yurukov
  - ultibo
  - systemcatch
  - bogomil
  - Pantkowsky
  - MindFreeze
country: BG
delays:
  production: 5
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 381.3939909342473
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 521.5300718641905
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 587.0303330732122
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 462.9122353077049
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 460.9409896435926
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 404.5812107767518
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 455.49078336598444
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 1057.262766
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1075.5
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 1123.53
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 419.8221756
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 412.38
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 410.39
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 381.3939909342473
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 521.5300718641905
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 587.0303330732122
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 462.9122353077049
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 460.9409896435926
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 404.5812107767518
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 455.49078336598444
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 544.2
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 529.03
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 584.01
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 473.6
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 471.77
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 414.95
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 468.93
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 538.05
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 383.65
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1067.4905370000001
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1085.727771
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 1183.53
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 539.8221756
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 532.38
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 530.39
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 544.2
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 529.03
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 584.01
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 473.6
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 471.77
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 414.95
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 468.93
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 538.05
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 383.65
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 27.73333333
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.004116843895948352
        coal: 0.485891091160113
        gas: 0.009672242118495794
        geothermal: 2.0252960205889294e-07
        hydro: 0.11224649230455917
        hydro discharge: 0.022464241676399814
        nuclear: 0.3043610315651058
        oil: 1.0324367892652374e-06
        solar: 0.026387890654927474
        unknown: 1.789443091966909e-05
        wind: 0.03484095220868181
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.005547402690548412
        coal: 0.4690319518066637
        gas: 0.010369936670194684
        geothermal: 4.5071619512471826e-07
        hydro: 0.09182828143035204
        hydro discharge: 0.02243052468801112
        nuclear: 0.3364750137656216
        oil: 3.2957624020129194e-06
        solar: 0.02886316804226203
        unknown: 8.341974537039722e-05
        wind: 0.03536638652852098
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0065746767309123365
        coal: 0.47836869592223386
        gas: 0.03126315770466536
        geothermal: 2.4573252052586532e-05
        hydro: 0.07104386120450264
        hydro discharge: 0.015652302625031787
        nuclear: 0.3306850100373881
        oil: 8.972763287432408e-06
        solar: 0.028758767590565826
        unknown: 4.5911349816201954e-05
        wind: 0.037574008451517274
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0044516565857140224
        coal: 0.3961948960008475
        gas: 0.07910572174146996
        geothermal: 3.2790621803616324e-05
        hydro: 0.12313690950388645
        hydro discharge: 0.00017561523941329556
        nuclear: 0.33968519068349146
        oil: 8.009500239041465e-06
        solar: 0.025997569264407435
        unknown: 1.6822589461300927e-05
        wind: 0.03119473159756308
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.005157748409723733
        coal: 0.39040770958641746
        gas: 0.08645776136082617
        geothermal: 5.147901791125278e-05
        hydro: 0.09093891853035717
        hydro discharge: 5.1926957177506517e-05
        nuclear: 0.365418262734482
        oil: 1.0166871816622023e-05
        solar: 0.02767342834466705
        unknown: 9.851471706379758e-05
        wind: 0.03373398121690895
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.005476322414417118
        coal: 0.3307893243669229
        gas: 0.09692471611252587
        geothermal: 0.00020603595395196666
        hydro: 0.09964617431392196
        hydro discharge: 0.002714113044972313
        nuclear: 0.3984595588246027
        oil: 1.536402545773523e-05
        solar: 0.026395492249138692
        unknown: 0.00029088728245925383
        wind: 0.03908187173623354
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.005342193110960644
        coal: 0.3871492852885874
        gas: 0.08945539458529987
        geothermal: 0.0001340583316482556
        hydro: 0.11806211360604908
        hydro discharge: 0.002252735999419624
        nuclear: 0.34116105424254795
        oil: 6.693021434711606e-06
        solar: 0.025154055058312863
        unknown: 5.9672232598778346e-05
        wind: 0.031222710384239648
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.005951578573705989
        coal: 0.45450672543034143
        gas: 0.07324586139060309
        geothermal: 6.246236388661088e-05
        hydro: 0.08085308001130906
        hydro discharge: 8.27577713634615e-05
        nuclear: 0.32387569343161665
        oil: 5.602225308020602e-05
        solar: 0.03067454989563182
        unknown: 6.173662793511683e-05
        wind: 0.030629440472515222
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.006000224348939999
        coal: 0.30061985177232936
        gas: 0.09255978379730964
        geothermal: 0.0002534442619831993
        hydro: 0.1005491271235462
        hydro discharge: 0.0003474704973627794
        nuclear: 0.3841046086180597
        oil: 4.630748454967646e-05
        solar: 0.0679523543839291
        unknown: 0.0002443461922414152
        wind: 0.047322336428580386
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: BG.fetch_production
  productionCapacity: ENTSOE.fetch_production_capacity
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Sofia
