bounding_box:
  - - -139.56020662181913
    - 47.80609772300011
  - - -113.53745235883926
    - 60.50005890629359
capacity:
  biomass: 838
  gas: 507
  hydro: 15910
  solar: 1
  wind: 704
contributors:
  - daveachuk
country: CA
emissionFactors:
  direct:
    unknown:
      - datetime: '2019-01-01'
        source: assumes 87% hydro, 5% biomass, 4% gas, 2% wind and 2% from various sources
        value: 28.6
  lifecycle:
    battery discharge:
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 71.89
    hydro discharge:
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 71.89
    unknown:
      - datetime: '2019-01-01'
        source: assumes 87% hydro, 5% biomass, 4% gas, 2% wind and 2% from various sources
        value: 56
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 1.635188256556211e-05
        biomass: 0.0005584396582173192
        coal: 0.007030034038303682
        gas: 0.024208569358771827
        geothermal: 0.00013319928459371534
        hydro: 0.0674617247639158
        hydro discharge: 6.316768948327749e-08
        nuclear: 0.009595371984369043
        oil: 0.0002778535309829377
        solar: 0.0025719354075286094
        unknown: 0.8681562018832593
        wind: 0.019990234379693793
isLowCarbon:
  unknown:
    - datetime: '2019-01-01'
      source: assumes 87% hydro, 5% biomass, 4% gas, 2% wind and 2% from various sources
      value: 0.94
isRenewable:
  unknown:
    - datetime: '2019-01-01'
      source: assumes 87% hydro, 5% biomass, 4% gas, 2% wind and 2% from various sources
      value: 0.94
parsers:
  consumption: CA_BC.fetch_consumption
region: Americas
timezone: America/Vancouver
