bounding_box:
  - - 12.2401111182
    - 48.5553052842
  - - 18.8531441586
    - 51.1172677679
capacity:
  biomass:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 510.0
  coal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 8360.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 8400.0
  gas:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1620.0
  hydro:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1112.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 1106.0
  hydro storage:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1172.0
  nuclear:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 4040.0
  oil:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 0.0
  solar:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 2083.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 3548.0
  unknown:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 410.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 460.0
  wind:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 339.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 342.0
contributors:
  - corradio
  - Frantisek12
country: CZ
delays:
  production: 7
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 485.6853601072458
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 647.450011043009
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 601.0350299075726
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 579.647486517319
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 544.8458365483311
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 492.5514382709734
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 535.9666012313977
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 1055.667306
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1055.67
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 1051.99
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 419.8221756
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 412.38
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 364.25
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 485.6853601072458
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 647.450011043009
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 601.0350299075726
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 579.647486517319
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 544.8458365483311
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 492.5514382709734
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 535.9666012313977
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 616.26
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 637.33
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 591.47
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 569.71
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 533.7
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 478.91
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 523.63
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 533.3
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 468.92
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1061.99227
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1061.994964
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 1111.99
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 539.8221756
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 532.38
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 484.25
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 616.26
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 637.33
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 591.47
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 569.71
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 533.7
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 478.91
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 523.63
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 533.3
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 468.92
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 34.33333333
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.030775967008316706
        coal: 0.508990139588575
        gas: 0.04682815190009607
        geothermal: 6.969628377469148e-06
        hydro: 0.02383877173283548
        hydro discharge: 0.0151380310872164
        nuclear: 0.2893962479735372
        oil: 0.0013204246546895928
        solar: 0.028287106244730117
        unknown: 0.035394930638582046
        wind: 0.020023226477726783
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.030123638979132294
        coal: 0.512515033708344
        gas: 0.06500299362507994
        geothermal: 1.28289192997832e-05
        hydro: 0.027924618338267728
        hydro discharge: 0.013354781998049363
        nuclear: 0.26492360356305455
        oil: 0.001763408303967414
        solar: 0.027958654790927358
        unknown: 0.03741541915414262
        wind: 0.019005099091007793
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.028982811521995267
        coal: 0.47289401730372455
        gas: 0.06210552841442711
        geothermal: 1.6609424120172853e-05
        hydro: 0.022193825789418233
        hydro discharge: 0.013979960694836754
        nuclear: 0.30044857822219234
        oil: 0.0016925009700699705
        solar: 0.02968129997233052
        unknown: 0.0423353243467738
        wind: 0.02566953090234451
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03131871062640971
        coal: 0.4569472438332179
        gas: 0.06275084426218422
        geothermal: 1.635741338651803e-05
        hydro: 0.02211736650279684
        hydro discharge: 0.012894584845943791
        nuclear: 0.3184942738681783
        oil: 0.0012220996767060152
        solar: 0.031638689889596644
        unknown: 0.03812856178919182
        wind: 0.02447119557550498
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.029463849772581333
        coal: 0.4160086970139699
        gas: 0.08566772698285684
        geothermal: 1.9247494865087226e-05
        hydro: 0.02461472696962768
        hydro discharge: 0.014050509553363613
        nuclear: 0.3290257130668433
        oil: 0.0014056105813524565
        solar: 0.032596319432724986
        unknown: 0.03816298928346639
        wind: 0.02898456728037031
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03678161504591727
        coal: 0.36251547256094496
        gas: 0.09981332039861046
        geothermal: 3.17992686488168e-05
        hydro: 0.028591134537821434
        hydro discharge: 0.016842005200248263
        nuclear: 0.338608205571207
        oil: 0.0021941142950996986
        solar: 0.03613637177932495
        unknown: 0.038917960981351876
        wind: 0.0395679702199244
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03446197378596682
        coal: 0.40031782305670743
        gas: 0.10240797690210954
        geothermal: 1.5507423976145894e-05
        hydro: 0.031275921762716964
        hydro discharge: 0.014163061549296689
        nuclear: 0.3260330491819357
        oil: 0.0015651849489020729
        solar: 0.03346104366725906
        unknown: 0.02819193849858886
        wind: 0.028106489996618935
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03325593502264791
        coal: 0.4360471128957177
        gas: 0.06954076162156766
        geothermal: 1.6227721794414462e-05
        hydro: 0.026305290266948805
        hydro discharge: 0.012173218061753775
        nuclear: 0.3227586505628027
        oil: 0.0017339846876074777
        solar: 0.03770335233005534
        unknown: 0.026844888249048546
        wind: 0.03362051145011616
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 3.0873600829250097e-10
        biomass: 0.03068194971037444
        coal: 0.4153746595745559
        gas: 0.044646539999568635
        geothermal: 1.745037666070874e-05
        hydro: 0.030971694749324846
        hydro discharge: 0.014375482874694569
        nuclear: 0.3648607780595693
        oil: 0.001557513730154071
        solar: 0.04804938073762329
        unknown: 0.012147890518926507
        wind: 0.037316606257218124
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: CZ.fetch_production
  productionCapacity: ENTSOE.fetch_production_capacity
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Prague
