_comment: Hydro capacities from Fraunhofer include capacities in AT, CH, LU which
  are directly connected to the German grid. Fraunhofer has no values for geothermal
  and unknown - these are from BNetz
bounding_box:
  - - 5.8227539063
    - 47.2643200803
  - - 15.0732421875
    - 55.1537662685
capacity:
  battery storage:
    - datetime: '2023-01-01'
      source: Fraunhofer ISE
      value: 7875.0
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 4379.0
  biomass:
    - datetime: '2023-01-01'
      source: Fraunhofer ISE
      value: 9030.0
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 8911.0
  coal:
    - datetime: '2023-01-01'
      source: Fraunhofer ISE
      value: 37489.0
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 37679.0
  gas:
    - datetime: '2023-01-01'
      source: Fraunhofer ISE
      value: 34799.0
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 34250.0
  geothermal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 56
  hydro:
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 6186.0
  hydro storage:
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 9699.0
  nuclear:
    - datetime: '2023-04-15'
      source: Fraunhofer ISE
      value: 0.0
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 4056.0
  oil:
    - datetime: '2023-01-01'
      source: Fraunhofer ISE
      value: 4682.0
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 4689.0
  solar:
    - datetime: '2023-01-01'
      source: Fraunhofer ISE
      value: 81824.0
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 67563.0
  unknown:
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 2766.0
  wind:
    - datetime: '2023-01-01'
      source: Fraunhofer ISE
      value: 69485.0
    - datetime: '2022-01-01'
      source: Fraunhofer ISE
      value: 66189.0
contributors:
  - corradio
  - bohne13
  - chiefymuc
  - nessie2013
  - IV1T3
  - sin
country: DE
delays:
  production: 7
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 411.81880400813094
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 551.2101172680785
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 520.0985094097524
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 491.1904039299606
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 410.23558916667355
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 363.2165970493008
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 419.4076679907016
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 1073.03112
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1087.81
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 1018.94
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 472.8075167
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 451.55
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 409.62
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 411.81880400813094
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 551.2101172680785
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 520.0985094097524
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 491.1904039299606
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 410.23558916667355
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 363.2165970493008
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 419.4076679907016
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 641.08
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 543.33
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 529.85
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 498.99
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 467.76
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 383.8
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 333.52
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 392.17
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 415.84
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 325.24
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1152.3866810000002
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1167.165561
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 1078.94
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 592.8075167
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 571.55
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 529.62
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 543.33
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 529.85
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 498.99
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 467.76
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 383.8
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 333.52
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 392.17
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 415.84
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 325.24
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 885.08
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 35.11666667
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.06822443423425736
        coal: 0.39198386333236024
        gas: 0.03157431710722741
        geothermal: 0.00020773144243425417
        hydro: 0.029805468813518508
        hydro discharge: 0.013915672985820294
        nuclear: 0.17043149438525243
        oil: 0.003294290586036577
        solar: 0.06364244279140722
        unknown: 0.08649548813526689
        wind: 0.14042479977885236
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07708897764813215
        coal: 0.3827977278598596
        gas: 0.05152664075008046
        geothermal: 0.00030081762386774055
        hydro: 0.03672522276589633
        hydro discharge: 0.014527289954485342
        nuclear: 0.1592289987002553
        oil: 0.0032084169946244513
        solar: 0.062710674255393
        unknown: 0.0744186951604695
        wind: 0.13746654028171984
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07835332511998744
        coal: 0.353146668422233
        gas: 0.05499511783969675
        geothermal: 0.00028879331641998524
        hydro: 0.031400407429919536
        hydro discharge: 0.014867379883969883
        nuclear: 0.1383594460405743
        oil: 0.003389170649212863
        solar: 0.06454637152936492
        unknown: 0.07742631234522791
        wind: 0.18322700658034122
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07900894954749245
        coal: 0.3603081765564477
        gas: 0.08477630064661429
        geothermal: 0.0002941900295092904
        hydro: 0.03300729924695468
        hydro discharge: 0.016691553724927418
        nuclear: 0.14397477614935936
        oil: 0.0050357221706694094
        solar: 0.07397814668449225
        unknown: 0.010377613475845949
        wind: 0.1925472703450103
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.08334123531362124
        coal: 0.27983556770896395
        gas: 0.10919225384594951
        geothermal: 0.0003304732632658129
        hydro: 0.03609500612428763
        hydro discharge: 0.01617399677781752
        nuclear: 0.1540946157192827
        oil: 0.007387950435001032
        solar: 0.07837966521002442
        unknown: 0.009727136677122536
        wind: 0.2254421010846722
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.08702404970930111
        coal: 0.23050551719977977
        gas: 0.12229414859323079
        geothermal: 0.0003783561864807586
        hydro: 0.04297840724642777
        hydro discharge: 0.019933356882951583
        nuclear: 0.13858323079322574
        oil: 0.007514822494521679
        solar: 0.08932299862069627
        unknown: 0.011447252495483323
        wind: 0.2500178597562115
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.08755809157361114
        coal: 0.2862686111476826
        gas: 0.1050167543268765
        geothermal: 0.00036271639509559753
        hydro: 0.043631298742318386
        hydro discharge: 0.016338422406075602
        nuclear: 0.14090159238819888
        oil: 0.006090105536354899
        solar: 0.08844532974189268
        unknown: 0.01076382812043977
        wind: 0.21462324869644384
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0905233514395519
        coal: 0.32699730143100636
        gas: 0.08142510335710512
        geothermal: 0.00037286151418963493
        hydro: 0.040725789129574384
        hydro discharge: 0.019044344315966497
        nuclear: 0.07454845518754781
        oil: 0.005467934783293558
        solar: 0.10708541467143354
        unknown: 0.009470082436569428
        wind: 0.24433935872694365
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 2.2362291587382914e-08
        biomass: 0.0937474861141913
        coal: 0.24549005828042275
        gas: 0.11093817647781459
        geothermal: 0.0003802823787645332
        hydro: 0.05836906940243982
        hydro discharge: 0.022539538205084253
        nuclear: 0.04297820396617949
        oil: 0.006206706660521965
        solar: 0.11673449612310911
        unknown: 0.009093485104513127
        wind: 0.29352247417925786
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: NORDPOOL.fetch_price
  production: ENTSOE.fetch_production
  productionCapacity: DE.fetch_production_capacity
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Berlin
