bounding_box:
  - - 14.7
    - 54.9
  - - 15.2
    - 55.2
capacity:
  wind: 30
contributors:
  - corradio
country: DK
delays:
  production: 6
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 13.719566539650941
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 12.549402358765795
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 2.276763925514579
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 7.380585911804152
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 845.5332093
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 845.53
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 720.51
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 336.9719859
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 336.97
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 299.26
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 13.719566539650941
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 12.549402358765795
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 2.276763925514579
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 7.380585911804152
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 1193.417464
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1193.42
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 641.08
  lifecycle:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 59.75
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 68.46
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 70.97
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 51.25
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 67.11
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 70.36
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 56.11
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 914.3278173
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 914.324608
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 780.51
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 456.9719859
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 456.97
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 419.26
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 59.75
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 68.46
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 70.97
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 51.25
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 67.11
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 70.36
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 56.11
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1437.417464
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1437.42
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 885.08
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 34.3
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.15661168716629678
        coal: 0.00331716485371506
        gas: 0.0016947962005256904
        geothermal: 0.0
        hydro: 0.1213849962993853
        hydro discharge: 0.00011383273255180241
        nuclear: 0.11550117235524167
        oil: 0.00017066502738564176
        solar: 0.09543327709934693
        unknown: 0.029608490643962444
        wind: 0.4761488688334596
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.1577679261710226
        coal: 0.010102791694210989
        gas: 0.003811377425800692
        geothermal: 0.0
        hydro: 0.1221603341598463
        hydro discharge: 5.702188158680028e-05
        nuclear: 0.12619386452024245
        oil: 0.00020779371259469363
        solar: 0.06867820829943942
        unknown: 0.03323026925657784
        wind: 0.4777681685347696
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.16579238628603746
        coal: 0.0103196850134556
        gas: 0.004944158298209431
        geothermal: 0.0
        hydro: 0.10028632088914455
        hydro discharge: 0.00012300835957443446
        nuclear: 0.10700798068412624
        oil: 0.0002645191412878521
        solar: 0.10247316800846068
        unknown: 0.027461606041351932
        wind: 0.48128971215388905
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.12225448945433968
        coal: 0.0021751993397026315
        gas: 0.0022269082439102445
        geothermal: 0.0
        hydro: 0.1242888735294987
        hydro discharge: 0.0007752581808694886
        nuclear: 0.1066827893340766
        oil: 6.888264190269998e-05
        solar: 0.10613271357724735
        unknown: 0.027389343179609615
        wind: 0.5079633589390947
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.1509817039745894
        coal: 0.005120003677044701
        gas: 0.004032555733722113
        geothermal: 0.0
        hydro: 0.12330590788159818
        hydro discharge: 0.0008623860233943704
        nuclear: 0.12512843409562846
        oil: 0.00019588033765653378
        solar: 0.08727843387655994
        unknown: 0.052260493816852584
        wind: 0.45079278422964475
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.21458586633562585
        coal: 0.0019538542747158183
        gas: 0.0009122916441096708
        geothermal: 0.0
        hydro: 0.11651761855820125
        hydro discharge: 0.00018349906981491427
        nuclear: 0.10498223710745579
        oil: 6.915450019144158e-05
        solar: 0.10671342758551561
        unknown: 0.027903863650514067
        wind: 0.42613263203214535
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.15092294864083675
        coal: 0.0022783206842212386
        gas: 0.0009285224506000643
        geothermal: 9.224343836678565e-08
        hydro: 0.12336904953145177
        hydro discharge: 0.00019274266446739864
        nuclear: 0.10137189514928194
        oil: 0.00010068371297734653
        solar: 0.12396973880209627
        unknown: 0.022760699443250893
        wind: 0.4740638893735513
parsers:
  price: ENTSOE.fetch_price
  production: BORNHOLM_POWERLAB.fetch_production
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Copenhagen
