bounding_box:
  - - 7.60472
    - 54.509132
  - - 13.30324
    - 57.751949
capacity:
  biomass: 2139
  coal: 3022
  gas: 1568
  geothermal: 0
  hydro: 5
  hydro storage: 0
  nuclear: 0
  oil: 959
  solar: 2322
  unknown: 136
  wind: 7017
contributors:
  - corradio
  - Manu1400
country: DK
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 175.6679542184547
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 147.06649839805567
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 112.24825613718873
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 146.43134312177915
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 845.5332093
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 845.53
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 720.51
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 336.9719859
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 336.97
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 299.26
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 175.6679542184547
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 147.06649839805567
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 112.24825613718873
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 146.43134312177915
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 1193.417464
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1193.42
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 641.08
  lifecycle:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 237.98
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 261.38
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 214.96
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 170.45
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 212.25
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 185.06
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 148.55
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 914.3278173
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 914.324608
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 780.51
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 456.9719859
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 456.97
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 419.26
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 237.98
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 261.38
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 214.96
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 170.45
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 212.25
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 185.06
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 148.55
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1437.417464
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1437.42
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 885.08
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 35.98888889
    wind:
      datetime: '2014-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.13592492222233807
        coal: 0.14862982190567306
        gas: 0.05243304314606192
        geothermal: 2.5875053975861645e-05
        hydro: 0.17118696548583506
        hydro discharge: 0.0007676193340449683
        nuclear: 0.05942030791063363
        oil: 0.018623963649979692
        solar: 0.028327849551991077
        unknown: 0.016247130929536672
        wind: 0.3684124799041742
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.12473034790927884
        coal: 0.1830027791670382
        gas: 0.07250546466378499
        geothermal: 3.7093131810531e-05
        hydro: 0.14882203948172829
        hydro discharge: 0.0010889733389942806
        nuclear: 0.06046818511131745
        oil: 0.00536568379704825
        solar: 0.03742373300803103
        unknown: 0.011301405058050388
        wind: 0.35525422403867085
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.1302385300023112
        coal: 0.12367906557685283
        gas: 0.08012253042259411
        geothermal: 4.900994023589188e-05
        hydro: 0.12222085324381182
        hydro discharge: 0.0012989553151573669
        nuclear: 0.07081292924741747
        oil: 0.007265412815763664
        solar: 0.039329219870263915
        unknown: 0.014678103706994723
        wind: 0.4103053343697566
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.10538214223210597
        coal: 0.09857289527064991
        gas: 0.05976135190773078
        geothermal: 2.4966548914023387e-05
        hydro: 0.21046337412355856
        hydro discharge: 0.006434456717977318
        nuclear: 0.05480553159864313
        oil: 0.006290878091412335
        solar: 0.044510226789154735
        unknown: 0.013863299453397133
        wind: 0.3998907796435825
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.13189276104943928
        coal: 0.13136732304235366
        gas: 0.06480312036465781
        geothermal: 2.728614489170488e-05
        hydro: 0.1706832141314521
        hydro discharge: 0.013076042085471204
        nuclear: 0.057434396493200854
        oil: 0.0075843835224256775
        solar: 0.04169909263375615
        unknown: 0.018244783224464246
        wind: 0.36318754620577526
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.11564883417132546
        coal: 0.11350646720722249
        gas: 0.05415225727705998
        geothermal: 2.1855654341671995e-05
        hydro: 0.14405692570895318
        hydro discharge: 0.002290166886259146
        nuclear: 0.07009152272995159
        oil: 0.006861905226122769
        solar: 0.05770264519227627
        unknown: 0.01746352171068468
        wind: 0.4182038478752183
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 2.7660562249715427e-10
        biomass: 0.10076243277817098
        coal: 0.07802998721771948
        gas: 0.052413102928163244
        geothermal: 2.159100507526037e-05
        hydro: 0.16225890448522592
        hydro discharge: 0.0021447687404075916
        nuclear: 0.06548243617681321
        oil: 0.007015599575435486
        solar: 0.07599253813957332
        unknown: 0.015436723322028813
        wind: 0.4404418556079665
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
subZoneNames:
  - DK-DK1
  - DK-DK2
  - DK-BHM
timezone: Europe/Copenhagen
