bounding_box:
  - - 0.712168816000087
    - 38.33180940700015
  - - 2.123057488000086
    - 39.618882554000066
contributors:
  - hectorespert
  - systemcatch
  - alixunderplatz
  - silimotion
country: ES
delays:
  production: 5
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 597.7507608049816
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 398.58747156879605
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 442.5750739383493
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 971.2573613
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1156.28
    gas:
      - datetime: '2017-01-01'
        source: EU-ETS, REE
        value: 618.289
      - datetime: '2018-01-01'
        source: EU-ETS, REE
        value: 590.329
      - datetime: '2019-01-01'
        source: EU-ETS, REE
        value: 583.131
      - datetime: '2020-01-01'
        source: EU-ETS, REE
        value: 635.217
      - datetime: '2021-01-01'
        source: EU-ETS, REE
        value: 581.127
      - datetime: '2022-01-01'
        source: EU-ETS, REE
        value: 570.7
    hydro discharge:
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 597.7507608049816
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 398.58747156879605
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 442.5750739383493
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
  lifecycle:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 508.96
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 545.25
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 591.87
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 429.89
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 432.34
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 484.68
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 425.57
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1050.5643503
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1235.586989
    gas:
      - datetime: '2017-01-01'
        source: EU-ETS, REE; IPCC 2014
        value: 738.289
      - datetime: '2018-01-01'
        source: EU-ETS, REE; IPCC 2014
        value: 710.329
      - datetime: '2019-01-01'
        source: EU-ETS, REE; IPCC 2014
        value: 703.131
      - datetime: '2020-01-01'
        source: EU-ETS, REE; IPCC 2014
        value: 755.217
      - datetime: '2021-01-01'
        source: EU-ETS, REE; IPCC 2014
        value: 701.127
      - datetime: '2022-01-01'
        source: EU-ETS, REE; IPCC 2014
        value: 690.7
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 508.96
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 545.25
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 591.87
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 429.89
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 432.34
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 484.68
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 425.57
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.9804187807295244
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0006599582731124307
        solar: 0.01887786648077494
        unknown: 0.0
        wind: 0.0
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0112917258329075
        coal: 0.08157607065119638
        gas: 0.8807455679404854
        geothermal: 0.0
        hydro: 0.005548580564484378
        hydro discharge: 0.00011696767994553189
        nuclear: 0.0096008616487973
        oil: 0.0004104775292249344
        solar: 0.0028405159451156603
        unknown: 0.00022116939787927693
        wind: 0.007644272356256877
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.04879515994862532
        coal: 0.3113157985487584
        gas: 0.4783351262876257
        geothermal: 0.0
        hydro: 0.025752150633954432
        hydro discharge: 0.00043960323421478266
        nuclear: 0.0579500630688144
        oil: 0.0033878144714261406
        solar: 0.026585250560806382
        unknown: 0.001130640621587394
        wind: 0.046308364587372385
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.05534416847944868
        coal: 0.05858218496343658
        gas: 0.674863503781332
        geothermal: 0.0
        hydro: 0.03910623638206724
        hydro discharge: 0.0006057334167077712
        nuclear: 0.0687038605636672
        oil: 0.0023725559220154767
        solar: 0.040500853928902694
        unknown: 0.001454754479110431
        wind: 0.05846432618000897
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.05134102664813793
        coal: 0.013737895125235395
        gas: 0.7757725977318239
        geothermal: 0.0
        hydro: 0.02764322927002764
        hydro discharge: 0.00038744858023824513
        nuclear: 0.04118737170398718
        oil: 0.0015182406358155598
        solar: 0.04526841911933494
        unknown: 0.0008968091257801603
        wind: 0.042227322659733675
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.04737205749277377
        coal: 0.012914991469643833
        gas: 0.8322256128466006
        geothermal: 0.0
        hydro: 0.008308067822092435
        hydro discharge: 0.0004406216408252614
        nuclear: 0.022573370674511244
        oil: 0.0006781928659262508
        solar: 0.049677877417665564
        unknown: 0.00041614514822784827
        wind: 0.02523681603575622
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.044695909195838754
        coal: 0.01216605388907611
        gas: 0.7206535014898646
        geothermal: 0.0
        hydro: 0.019753152153369546
        hydro discharge: 0.004812602557969174
        nuclear: 0.04685582364530051
        oil: 0.00045709713952712835
        solar: 0.09811719843679369
        unknown: 0.0023410987420485673
        wind: 0.05014708177253071
parsers:
  consumption: ES.fetch_consumption
  production: ES.fetch_production
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, REE:
    link: https://colab.research.google.com/github/silimotion/Emission_factors_research/blob/main/Spanish_non_peninsular_factors.ipynb
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Madrid
