bounding_box:
  - - 1.850759311000076
    - 38.76906972900008
  - - 3.974375847000147
    - 40.46877676000017
contributors:
  - hectorespert
  - systemcatch
  - alixunderplatz
country: ES
delays:
  production: 5
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 603.8409632075713
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 529.9127397853163
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 331.0240049348508
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 338.22390791888375
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 971.2573613
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1156.28
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 397.8527093
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 426.61
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 603.8409632075713
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 529.9127397853163
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 331.0240049348508
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 338.22390791888375
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
  lifecycle:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 545.2
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 780.94
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 611.15
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 414.46
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 427.66
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 480.51
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 398.84
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1050.5643503
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1235.586989
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 517.8527093
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 546.61
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 545.2
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 780.94
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 611.15
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 414.46
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 427.66
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 480.51
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 398.84
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07012595966354988
        coal: 0.13707874124524647
        gas: 0.7393269371565881
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.052246772607011174
        unknown: 0.0012160741241621646
        wind: 0.0
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0779828345111624
        coal: 0.5745876055279928
        gas: 0.3053327802187535
        geothermal: 0.0
        hydro: 0.005451131532608672
        hydro discharge: 0.0001147784099435192
        nuclear: 0.008630081205104514
        oil: 0.0003915043952391435
        solar: 0.019386543100322836
        unknown: 0.00021447416254085012
        wind: 0.007906216803809357
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.06348458816893125
        coal: 0.408676408932328
        gas: 0.31031772477722613
        geothermal: 0.0
        hydro: 0.03384871898163168
        hydro discharge: 0.0006004356675192989
        nuclear: 0.07816490396321667
        oil: 0.00321082797700781
        solar: 0.03882117896044699
        unknown: 0.001509028069063085
        wind: 0.06136721586630992
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.060640280530438205
        coal: 0.06202178221978827
        gas: 0.6344414344754298
        geothermal: 1.622966670602271e-08
        hydro: 0.04579397110565894
        hydro discharge: 0.0007657210850790533
        nuclear: 0.07792010946022973
        oil: 0.002479595528790659
        solar: 0.048563336513707846
        unknown: 0.0016485527401643156
        wind: 0.06572516765171323
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.05548351924513254
        coal: 0.01509489488459658
        gas: 0.7627202276917064
        geothermal: 7.3422915784439354e-09
        hydro: 0.02825344392266803
        hydro discharge: 0.00042219889777420934
        nuclear: 0.04199008339330721
        oil: 0.0010795371307786117
        solar: 0.05181717041974183
        unknown: 0.0009162298814908619
        wind: 0.04222276306085863
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.05445758257824762
        coal: 0.020921812745093193
        gas: 0.8035316268273758
        geothermal: 0.0
        hydro: 0.009124459880428294
        hydro discharge: 0.00040806004105304943
        nuclear: 0.023987786261196593
        oil: 0.0004494674463574116
        solar: 0.060264359888284706
        unknown: 0.00045313626017145326
        wind: 0.026401348297071654
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.056605763785542086
        coal: 0.01908548352757247
        gas: 0.6479675752149817
        geothermal: 2.221486747199871e-09
        hydro: 0.02458284794125593
        hydro discharge: 0.006709107682244837
        nuclear: 0.06102651574800958
        oil: 0.0006032269543081474
        solar: 0.1177845802219662
        unknown: 0.002975021716310309
        wind: 0.06265953732033644
parsers:
  consumption: ES.fetch_consumption
  production: ES.fetch_production
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Madrid
