_comment: 'Hydro capacity from IRENA includes pumped storage generation capacity.
  Note: ENTSO-E (not used for hydro capacity) lists 5645 MW for pumped storage CONSUMPTION
  capacity.'
bounding_box:
  - - -9.3603515625
    - 35.9957853864
  - - 3.6474609375
    - 43.6758180933
capacity:
  biomass:
    - datetime: '2022-12-01'
      source: ree.es
      value: 1219.0
    - datetime: '2024-09-01'
      source: ree.es
      value: 1222.0
  coal:
    - datetime: '2022-12-01'
      source: ree.es
      value: 3223.0
    - datetime: '2024-09-01'
      source: ree.es
      value: 1820.0
  gas:
    - datetime: '2022-12-01'
      source: ree.es
      value: 30160.0
    - datetime: '2023-12-01'
      source: ree.es
      value: 30152.0
    - datetime: '2024-09-01'
      source: ree.es
      value: 30088.0
  hydro:
    - datetime: '2022-12-01'
      source: ree.es
      value: 17093.0
    - datetime: '2023-12-01'
      source: ree.es
      value: 17096.0
    - datetime: '2024-09-01'
      source: ree.es
      value: 17097.0
  hydro storage:
    - datetime: '2022-12-01'
      source: ree.es
      value: 3331.0
  nuclear:
    - datetime: '2022-12-01'
      source: ree.es
      value: 7117.0
  solar:
    - datetime: '2022-12-01'
      source: ree.es
      value: 21815.0
    - datetime: '2023-12-01'
      source: ree.es
      value: 26866.0
    - datetime: '2024-09-01'
      source: ree.es
      value: 30070.0
  unknown:
    - datetime: '2022-12-01'
      source: ree.es
      value: 387.0
  wind:
    - datetime: '2022-12-01'
      source: ree.es
      value: 29556.0
    - datetime: '2023-12-01'
      source: ree.es
      value: 30100.0
    - datetime: '2024-09-01'
      source: ree.es
      value: 30848.0
contributors:
  - brandongalbraith
  - corradio
  - JosepRey
  - nessie2013
  - KabelWlan
  - gadakast
  - silimotion
country: ES
delays:
  production: 6
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 229.30897353813688
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 214.83170374364258
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 268.92210819495494
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 208.46210544431017
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 183.25464973718874
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 160.131608744309
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 140.2415453661764
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 971.2573613
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1156.28
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 1221.36
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 397.8527093
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 426.61
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 399.79
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 229.30897353813688
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 214.83170374364258
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 268.92210819495494
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 208.46210544431017
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 183.25464973718874
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 160.131608744309
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 140.2415453661764
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 641.08
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 271.55
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 206.49
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 258.89
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 200.09
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 177.97
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 151.02
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 133.85
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 183.8
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 109.3
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1050.5643503
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1235.586989
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 1281.36
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 517.8527093
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 546.61
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 519.79
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 271.55
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 206.49
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 258.89
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 200.09
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 177.97
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 151.02
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 133.85
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 183.8
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 109.3
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 885.08
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 26.46666667
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.024729649400220714
        coal: 0.1994616304155791
        gas: 0.17218400015166174
        geothermal: 2.198311266629953e-09
        hydro: 0.11872036535138755
        hydro discharge: 0.0006690508615017283
        nuclear: 0.23362247644985304
        oil: 0.011211442158969569
        solar: 0.049283682351388296
        unknown: 0.0049796422247172165
        wind: 0.1851380786522526
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.017400934688113337
        coal: 0.14331242065540795
        gas: 0.16420663715253075
        geothermal: 4.193977272960315e-08
        hydro: 0.15796575968235974
        hydro discharge: 0.0019735377153009864
        nuclear: 0.23805408139777148
        oil: 0.007506006992952079
        solar: 0.048069953377326946
        unknown: 0.03468219368922021
        wind: 0.18682842995981014
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.023015143021367132
        coal: 0.16668790945806417
        gas: 0.2246378807006261
        geothermal: 6.453757277894176e-08
        hydro: 0.08581610464262171
        hydro discharge: 0.001978966454856855
        nuclear: 0.24962656496042582
        oil: 0.009991675090770289
        solar: 0.05093707171750118
        unknown: 0.004932034696543194
        wind: 0.18237658818160007
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.022673456763081124
        coal: 0.13895930666592238
        gas: 0.20046767929901407
        geothermal: 9.811850531712586e-08
        hydro: 0.14618270156758603
        hydro discharge: 0.002091944148744422
        nuclear: 0.23977024015323556
        oil: 0.009677596798808447
        solar: 0.04734419202996424
        unknown: 0.005169729486155207
        wind: 0.18766352746437026
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.021771340508042605
        coal: 0.05022128399586975
        gas: 0.3016719608402146
        geothermal: 1.3983644433285595e-07
        hydro: 0.10802380397215207
        hydro discharge: 0.0017961965748222095
        nuclear: 0.2426052173018302
        oil: 0.010267872384282445
        solar: 0.05651332121041952
        unknown: 0.004757302443979581
        wind: 0.20237492625990242
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.02576940932970884
        coal: 0.023606793132869234
        gas: 0.25266322033346095
        geothermal: 3.071781651508848e-07
        hydro: 0.14329862247272515
        hydro discharge: 0.002217925764865566
        nuclear: 0.24710934127032938
        oil: 0.007858896117620475
        solar: 0.07968157381427653
        unknown: 0.005260289966137663
        wind: 0.21253455424561848
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.02663926531745853
        coal: 0.023842698711103824
        gas: 0.24310909189258814
        geothermal: 3.574840044114296e-07
        hydro: 0.13367005885475555
        hydro discharge: 0.001825554061755615
        nuclear: 0.2363500501986848
        oil: 0.006093150074518059
        solar: 0.09700712899968174
        unknown: 0.005219086262530957
        wind: 0.22624533100532643
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.024178323585088625
        coal: 0.031671741152688615
        gas: 0.29359571932273953
        geothermal: 1.3940721916209844e-07
        hydro: 0.08560148569777998
        hydro discharge: 0.002189338093915931
        nuclear: 0.21761711850155588
        oil: 0.0048068345553714574
        solar: 0.11345430412742653
        unknown: 0.004160224437288197
        wind: 0.22272569443118873
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 1.5825222235060013e-08
        biomass: 0.0211978649310854
        coal: 0.016028241556231476
        gas: 0.21704746917634757
        geothermal: 8.846343066579253e-08
        hydro: 0.10001944026410947
        hydro discharge: 0.024755108359468193
        nuclear: 0.22788225799233922
        oil: 0.001971551162991181
        solar: 0.14940009488035225
        unknown: 0.0031572278831574004
        wind: 0.23854097792830004
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionCapacity: REE.fetch_production_capacity
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Madrid
