bounding_box:
  - - -5.44921875
    - 42.3098154157
  - - 8.2177734375
    - 51.2894059027
capacity:
  battery storage:
    - datetime: '2021-01-01'
      source: rte-france.com
      value: 292.0
    - datetime: '2022-01-01'
      source: rte-france.com
      value: 476.0
  biomass:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 2272.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 2371.0
  coal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1816.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 1812.0
  gas:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 12893.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 13133.0
  geothermal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 2.0
  hydro:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 20482.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 20385.0
  hydro storage:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 5051.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 5065.0
  nuclear:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 61370.0
  oil:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 2566.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 3042.0
  solar:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 14639.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 17419.0
  unknown:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1388.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 1275.0
  wind:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 21336.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 23617.0
contributors:
  - corradio
  - lorrieq
  - nessie2013
  - gadakast
country: FR
delays:
  production: 6
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 43.31404704993305
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 68.95791686885718
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 84.57988955073837
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 58.81634145191706
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 59.80442699957435
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 61.10607257558027
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 66.82067058776849
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 854.4786144
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 869.45
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 923.04
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 380.5979557
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 381.61
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 391.79
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 43.31404704993305
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 68.95791686885718
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 84.57988955073837
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 58.81634145191706
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 59.80442699957435
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 61.10607257558027
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 66.82067058776849
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 769.5956561
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 755.44
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 657.06
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 40.42
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 57.1
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 65.52
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 44.3
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 45.31
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 45.43
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 50.86
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 83.04
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 43.69
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 953.9335274
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 968.9049130000001
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 983.04
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 500.5979557
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 501.61
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 511.79
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 40.42
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 57.1
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 65.52
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 44.3
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 45.31
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 45.43
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 50.86
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 83.04
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 43.69
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1013.5956561
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 999.44
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 901.06
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 30.075
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.014649714483554652
        coal: 0.01743473927467629
        gas: 0.042370588719523795
        geothermal: 3.8550414322331076e-07
        hydro: 0.09754615544021171
        hydro discharge: 0.009731422361683338
        nuclear: 0.7595048922765821
        oil: 0.004889142949567012
        solar: 0.013819388314986752
        unknown: 0.000614813699422456
        wind: 0.03943875386590272
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.01677123156475827
        coal: 0.01771380383168754
        gas: 0.07228349391741931
        geothermal: 1.1582844618221332e-06
        hydro: 0.10832503915402875
        hydro discharge: 0.009916686010319696
        nuclear: 0.71078728588206
        oil: 0.0032546299668737215
        solar: 0.01653651106912829
        unknown: 0.0023310125481720645
        wind: 0.04207914464919185
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.01874931741483195
        coal: 0.02217405839239406
        gas: 0.08042898038424726
        geothermal: 1.4443981629795167e-06
        hydro: 0.08912438727559667
        hydro discharge: 0.010577498427143008
        nuclear: 0.7052228220562244
        oil: 0.0066407261143321475
        solar: 0.017547622134321695
        unknown: 0.0020781193570661915
        wind: 0.04745501968992185
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.018035324023824167
        coal: 0.012904376129606734
        gas: 0.05857301777423757
        geothermal: 2.278213745683362e-06
        hydro: 0.11208681726951314
        hydro discharge: 0.010346822439173526
        nuclear: 0.7100193702858942
        oil: 0.003893280019216626
        solar: 0.019937308174457095
        unknown: 0.0009283615282052557
        wind: 0.05327304912631802
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.01871898207372967
        coal: 0.004781560487671986
        gas: 0.07366837060268415
        geothermal: 3.1795102296530352e-06
        hydro: 0.10127673989066836
        hydro discharge: 0.009748089354335208
        nuclear: 0.6984020424154658
        oil: 0.004555409825442723
        solar: 0.022878978795488204
        unknown: 0.0011220006251346408
        wind: 0.06484465527719976
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.020529301091895973
        coal: 0.004172785077081038
        gas: 0.07510950459256568
        geothermal: 5.268949262061907e-06
        hydro: 0.11846312275668504
        hydro discharge: 0.01021576888639212
        nuclear: 0.6587480009356248
        oil: 0.0019345536002706675
        solar: 0.026975745955167097
        unknown: 0.00133388970405835
        wind: 0.08251206496407885
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.01986776634745126
        coal: 0.010539286860876882
        gas: 0.07135179738829638
        geothermal: 1.2086467422343465e-05
        hydro: 0.10679002538398844
        hydro discharge: 0.009124341921299002
        nuclear: 0.6769027652161906
        oil: 0.002013989926045797
        solar: 0.027757770241203624
        unknown: 0.0011997711718508865
        wind: 0.07444042040811698
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.02204091187513789
        coal: 0.014601390823292728
        gas: 0.11580026111835967
        geothermal: 1.5621531134517534e-05
        hydro: 0.09250305918124437
        hydro discharge: 0.012216356787898088
        nuclear: 0.5976098526087545
        oil: 0.0032021254614866025
        solar: 0.04352581516462162
        unknown: 0.0025518795894696983
        wind: 0.09593274493916898
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 9.625087254396676e-07
        biomass: 0.014264428092724046
        coal: 0.00467771704550152
        gas: 0.06498282045318246
        geothermal: 4.345338864362472e-06
        hydro: 0.10486456106233935
        hydro discharge: 0.010891116750743777
        nuclear: 0.6433432648756232
        oil: 0.0034256244714812806
        solar: 0.04778889940927868
        unknown: 0.0012474106296712303
        wind: 0.10450885511740429
parsers:
  consumption: FR.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: NORDPOOL.fetch_price
  production: FR.fetch_production
  productionCapacity: ENTSOE.fetch_production_capacity
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Paris
