bounding_box:
  - - -8.673837442999911
    - 53.53457265800016
  - - -4.930775519999884
    - 55.81134674700017
capacity:
  battery storage: 150
  biomass: 82
  coal: 0
  gas: 1008
  hydro: 6
  oil: 394
  solar: 285
  wind: 1430
contributors:
  - corradio
  - systemcatch
  - brunolajoie
  - alixunderplatz
  - nessie2013
  - msaynevirta
  - brandongalbraith
country: GB
delays:
  production: 5
disclaimer: The complete generation mix is unavailable. It is therefore estimated
  by Electricity Maps.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 400.825862117709
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 410.5753050884724
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 351.3818106256959
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 330.8718346811666
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 302.56341118267267
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 304.7507814773746
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 295.25335109382246
    gas:
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 410.39
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 400.825862117709
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 410.5753050884724
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 351.3818106256959
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 330.8718346811666
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 302.56341118267267
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 304.7507814773746
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 295.25335109382246
    oil:
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 641.08
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 482.26120794293905
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 495.18349403296713
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 417.44
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 373.85
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 337.13
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 328.63
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 363.75
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 346.89
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 285.66
    gas:
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 530.39
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 482.26120794293905
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 495.18349403296713
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 417.44
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 373.85
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 337.13
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 328.63
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 363.75
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 346.89
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 285.66
    oil:
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 885.08
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.2731996571787163
        gas: 0.5208424904534642
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.001187650500454946
        solar: 0.0
        unknown: 0.0
        wind: 0.20476734818604286
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.272702648819229
        gas: 0.546145663975731
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0030721677803850164
        solar: 0.0
        unknown: 0.0
        wind: 0.1780767831357459
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.05618213937451059
        coal: 0.1338237794834609
        gas: 0.47453068805301524
        geothermal: 0.0
        hydro: 0.0027776339705401936
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.07187714569124433
        solar: 0.0
        unknown: 0.017777946299372332
        wind: 0.24302538053278433
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07214151414673074
        coal: 0.1433253076490959
        gas: 0.42888185117776256
        geothermal: 0.0
        hydro: 0.003011039601075656
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.00800763595148947
        solar: 0.0
        unknown: 0.029088990617660817
        wind: 0.3155374545180556
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07939208289373159
        coal: 0.09374512821023084
        gas: 0.4322629986241711
        geothermal: 0.0
        hydro: 0.0038138197525977363
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.008598078615118559
        solar: 0.0
        unknown: 0.02870487488604384
        wind: 0.3534766566209179
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.07900957953989912
        coal: 0.10254451441046267
        gas: 0.4006541300869623
        geothermal: 0.0
        hydro: 0.0037351887391979055
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.008467020003272971
        solar: 0.0
        unknown: 0.02820390031873462
        wind: 0.3773791864820577
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.08871192876669518
        coal: 0.12590938003773974
        gas: 0.4321900803345247
        geothermal: 0.0
        hydro: 0.0028765602389080225
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.007603360156160388
        solar: 0.0
        unknown: 0.02767487613864049
        wind: 0.3150271645789647
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.08445285682923925
        coal: 0.1198644240879961
        gas: 0.4114402539141438
        geothermal: 0.0
        hydro: 0.0027384721347124387
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.007238362473718337
        solar: 0.0
        unknown: 0.0263462358558941
        wind: 0.34791360506697827
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 1.2541538075768468e-09
        biomass: 0.0524001413642039
        coal: 0.041451006140377174
        gas: 0.4710320545058054
        geothermal: 2.1320614728806394e-08
        hydro: 0.013334461770763239
        hydro discharge: 0.001313038837150195
        nuclear: 0.05048390722006916
        oil: 0.001057669293005205
        solar: 0.018526790220281177
        unknown: 0.003474909037729321
        wind: 0.3469247310863472
parsers:
  consumption: SMARTGRIDDASHBOARD.fetch_consumption
  consumptionForecast: SMARTGRIDDASHBOARD.fetch_consumption_forecast
  generationForecast: SMARTGRIDDASHBOARD.fetch_total_generation
  price: ENTSOE.fetch_price
  production: SMARTGRIDDASHBOARD.fetch_production
  productionPerModeForecast: SMARTGRIDDASHBOARD.fetch_wind_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/London
