bounding_box:
  - - -3.933338995999918
    - 58.2306989600001
  - - -1.8924861319999025
    - 59.86090729400016
capacity:
  solar: 1.2
  wind: 48
contributors:
  - systemcatch
  - maxbellec
country: GB
delays:
  production: 5
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 500.43029243797986
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 461.9632215111321
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 479.9261719393477
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 460.40202785294656
    hydro discharge:
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 500.43029243797986
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 461.9632215111321
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 479.9261719393477
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 460.40202785294656
  lifecycle:
    battery discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 14.17
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 25.79
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 90.78
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 50.36
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 92.41
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 68.12
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 82.64
    hydro discharge:
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 14.17
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 25.79
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 90.78
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 50.36
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 92.41
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 68.12
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 82.64
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 43.6
    unknown:
      _comment: Source http://www.oref.co.uk/wp-content/uploads/2015/05/Orkney-wide-energy-audit-2014-Energy-Sources-and-Uses.pdf
      source: assumes 95% wind, 5% solar
      value: 14.169
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 1.0
        wind: 0.0
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.002714230464320721
        coal: 0.0030024422404439028
        gas: 0.017757415245395005
        geothermal: 0.0
        hydro: 0.0008037381224855953
        hydro discharge: 0.0003044860294197552
        nuclear: 0.00853243351061945
        oil: 6.667194092467053e-06
        solar: 0.0004506918211325169
        unknown: 0.9612493229779385
        wind: 0.005175317543492811
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.019339956530301055
        coal: 0.008143269193494472
        gas: 0.1347243364954034
        geothermal: 0.0
        hydro: 0.005228310195482785
        hydro discharge: 0.002050926089762473
        nuclear: 0.06860137056261482
        oil: 6.289759954195913e-05
        solar: 0.011495697178029543
        unknown: 0.7092177839233876
        wind: 0.041096264353967425
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0109552593211359
        coal: 0.0025531204519057362
        gas: 0.0643929579225949
        geothermal: 0.0
        hydro: 0.003048133581355537
        hydro discharge: 0.0009602481253311369
        nuclear: 0.03131731501784755
        oil: 8.894767169801107e-06
        solar: 0.005914117800233841
        unknown: 0.8575678354906368
        wind: 0.02324969674000338
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.022064907698469406
        coal: 0.007466415637156759
        gas: 0.13637649866978588
        geothermal: 0.0
        hydro: 0.00710232119643254
        hydro discharge: 0.0025521399301018616
        nuclear: 0.06501961365427432
        oil: 1.1620822767575181e-05
        solar: 0.012616142536719025
        unknown: 0.7053744676904489
        wind: 0.04136317136250298
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.012119495806002252
        coal: 0.004589822943932768
        gas: 0.09522529360129638
        geothermal: 0.0
        hydro: 0.005936222716983088
        hydro discharge: 0.001501445748018853
        nuclear: 0.03677799446257302
        oil: 1.254230345674135e-05
        solar: 0.010871619127210809
        unknown: 0.7908829171021404
        wind: 0.042036767762583443
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.017962880201221453
        coal: 0.004701847820464847
        gas: 0.12041364770421588
        geothermal: 0.0
        hydro: 0.015633915903732712
        hydro discharge: 0.0023311228983633574
        nuclear: 0.06131455970478311
        oil: 5.670478451393165e-05
        solar: 0.01770617274336336
        unknown: 0.6736889550786026
        wind: 0.0861334053531143
isLowCarbon:
  unknown:
    value: 1
isRenewable:
  unknown:
    value: 1
parsers:
  production: GB_ORK.fetch_production
region: Europe
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/London
