bounding_box:
  - - 16.2022982113
    - 45.7594811061
  - - 22.710531447
    - 48.6238540716
capacity:
  battery storage:
    - datetime: '2024-09-01'
      source: mavir.hu
      value: 35.3
  biomass:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 262.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 263.0
    - datetime: '2024-10-01'
      source: mavir.hu
      value: 384.5
  coal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 829.0
  gas:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 3151.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 3161.0
  geothermal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 3.0
  hydro:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 61.0
  nuclear:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1916.0
  oil:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 425.0
  solar:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 3300.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 3888.0
    - datetime: '2024-10-01'
      source: mavir.hu
      value: 3964.8
  unknown:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 92.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 106.0
  wind:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 323.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 325.0
contributors:
  - corradio
  - nessie2013
  - RolandSzep
country: HU
delays:
  production: 6
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 255.02554731207866
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 330.43700186109
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 310.88843611533713
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 310.5580525959209
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 276.2969269059795
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 257.0197542220101
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 262.3991679242528
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 1144.916957
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1211.37
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 1231.95
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 455.1593805
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 459.76
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 441.99
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 255.02554731207866
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 330.43700186109
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 310.88843611533713
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 310.5580525959209
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 276.2969269059795
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 257.0197542220101
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 262.3991679242528
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 837.58
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 641.08
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 370.58
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 363.32
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 350.9
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 347.78
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 318.68
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 299.36
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 303.91
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 307.08
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 259.77
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1157.920756
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1224.373799
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 1291.95
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 575.1593805
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 579.76
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 561.99
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 370.58
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 363.32
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 350.9
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 347.78
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 318.68
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 299.36
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 303.91
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 307.08
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 259.77
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1081.58
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 885.08
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 30.66666667
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.02677222961386532
        coal: 0.23672991692037493
        gas: 0.1192228005713514
        geothermal: 2.720560283512618e-06
        hydro: 0.057415051918715036
        hydro discharge: 0.00557896325253772
        nuclear: 0.4707830036160992
        oil: 0.002357019357480844
        solar: 0.006887734794729681
        unknown: 0.04905661546109503
        wind: 0.02522386696202215
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.026460157467515434
        coal: 0.22209115048696362
        gas: 0.14367645721246633
        geothermal: 4.43828199599571e-06
        hydro: 0.06836067575875206
        hydro discharge: 0.006122340290549228
        nuclear: 0.4561516923684028
        oil: 0.002417270394168044
        solar: 0.006402302671057955
        unknown: 0.04385857425789696
        wind: 0.024479133729618623
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.029560322327361343
        coal: 0.19494139097983196
        gas: 0.16990210432408584
        geothermal: 7.69777460301975e-06
        hydro: 0.07197878721359806
        hydro discharge: 0.008664233379496313
        nuclear: 0.44227544531422053
        oil: 0.0025402249310953156
        solar: 0.008140383236853104
        unknown: 0.04086145109297448
        wind: 0.03114139795759535
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.030572191439530556
        coal: 0.20407842515919233
        gas: 0.1624025766401251
        geothermal: 3.113484410089923e-05
        hydro: 0.07498946479015144
        hydro discharge: 0.0073938738415697
        nuclear: 0.4485768964564317
        oil: 0.002032040189596488
        solar: 0.007430801155111233
        unknown: 0.03370177682850838
        wind: 0.028790880727022093
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.034130320291713735
        coal: 0.16009673746777264
        gas: 0.1927037281654932
        geothermal: 1.1770098762067142e-05
        hydro: 0.08338862035584028
        hydro discharge: 0.009466531356156887
        nuclear: 0.4383642609396775
        oil: 0.0027098185903465495
        solar: 0.011971769982140647
        unknown: 0.030035961666726636
        wind: 0.037120484598063164
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.035600457524166795
        coal: 0.13400148717606747
        gas: 0.20605239450865326
        geothermal: 2.531415425298107e-05
        hydro: 0.08893261866516848
        hydro discharge: 0.012574996732910989
        nuclear: 0.4153482939783612
        oil: 0.002357873402002789
        solar: 0.03987893488994213
        unknown: 0.02781239914983111
        wind: 0.03741525827278109
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.033635225271806436
        coal: 0.13802591328860855
        gas: 0.2103979355172582
        geothermal: 5.280524160793029e-05
        hydro: 0.06856258487331086
        hydro discharge: 0.007601445176602368
        nuclear: 0.42373193778900164
        oil: 0.0027567275819791086
        solar: 0.05144766651344217
        unknown: 0.034576012168041036
        wind: 0.029211696256324
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03338228801149354
        coal: 0.1445231370881658
        gas: 0.18526171792727733
        geothermal: 2.5756482091646892e-05
        hydro: 0.06135050566940922
        hydro discharge: 0.008907584819965453
        nuclear: 0.4374856998526547
        oil: 0.00397490247247613
        solar: 0.06455884577094796
        unknown: 0.02892025425626989
        wind: 0.03160950113980783
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.027405973465588658
        coal: 0.12048861841156655
        gas: 0.16256058508773244
        geothermal: 4.230099857035289e-05
        hydro: 0.08443321987182296
        hydro discharge: 0.01002187409616397
        nuclear: 0.44556243443663957
        oil: 0.0027758263587770635
        solar: 0.08794673384846126
        unknown: 0.022267967988398335
        wind: 0.03649463693517092
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionCapacity: ENTSOE.fetch_production_capacity
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Budapest
