aggregates_displayed:
  - none
bounding_box:
  - - -117.12776
    - 14.5388286402
  - - -86.811982388
    - 32.72083
capacity:
  biomass:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 880.0
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 890.0
  coal:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 5380.0
  gas:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 44590.0
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 44950.0
  hydro:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 13300.0
  nuclear:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 1610.0
  solar:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 9360.0
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 10910.0
  unknown:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 6860.0
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 25940.0
  wind:
    - datetime: '2022-01-01'
      source: Ember, Yearly electricity data
      value: 7310.0
    - datetime: '2023-01-01'
      source: Ember, Yearly electricity data
      value: 7320.0
contributors:
  - scriptator
country: MX
emissionFactors:
  direct:
    unknown:
      - comment: Assumes a mix of 3.6% nuclear, 8.8% hydro, 8.4% oil, 63.4% gas, 4.2%
          coal, 4.3% solar, 5.9% wind, 1.5% other renewables with default IPCC 2014
          values.
        datetime: '2020-01-01'
        source: IEA, Electricity generation mix in Mexico, 1 Jan - 30 Sep, 2019 and
          2020, IEA, Paris
        value: 305
  lifecycle:
    unknown:
      - comment: Assumes a mix of 3.6% nuclear, 8.8% hydro, 8.4% oil, 63.4% gas, 4.2%
          coal, 4.3% solar, 5.9% wind, 1.5% other renewables with default IPCC 2014
          values.
        datetime: '2020-01-01'
        source: IEA, Electricity generation mix in Mexico, 1 Jan - 30 Sep, 2019 and
          2020, IEA, Paris
        value: 411
parsers:
  production: CENACE.fetch_production
  productionCapacity: EMBER.fetch_production_capacity
region: Americas
sources:
  IEA, Electricity generation mix in Mexico, 1 Jan - 30 Sep, 2019 and 2020, IEA, Paris:
    link: https://www.iea.org/data-and-statistics/charts/electricity-generation-mix-in-mexico-1-jan-30-sep-2019-and-2020
subZoneNames:
  - MX-BC
  - MX-BCS
  - MX-CE
  - MX-NE
  - MX-NO
  - MX-NW
  - MX-OC
  - MX-OR
  - MX-PN
timezone: America/Mexico_City
