bounding_box:
  - - 3.31497114423
    - 50.803721015
  - - 7.09205325687
    - 53.5104033474
capacity:
  biomass:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1201.0
  coal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 4006.0
  gas:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 18351.0
  geothermal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 0.0
  hydro:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 37.0
  hydro storage:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 0.0
  nuclear:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 486.0
  oil:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 0.0
  solar:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 22590.0
  unknown:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1.0
  wind:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 9410.0
contributors:
  - corradio
  - PaulCornelissen
  - nessie2013
  - VIKTORVAV99
country: NL
delays:
  production: 6
disclaimer: Solar production is collected from NED.nl and can contain their own estimations.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 329.707756493409
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 398.9380617448162
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 406.36987287594684
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 423.8974375890719
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 376.6182999967637
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 360.8000379385998
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 350.735060243539
    biomass:
      datetime: '2021-01-01'
      source: EU-ETS 2021
      value: 0.0
    coal:
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 799.37
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 402.3363923
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 401.09
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 404.39
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 329.707756493409
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 398.9380617448162
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 406.36987287594684
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 423.8974375890719
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 376.6182999967637
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 360.8000379385998
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 350.735060243539
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 480.09
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 496.29
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 471.72
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 459.53
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 414.66
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 381.33
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 388.46
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 357.41
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 301.11
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2012-01-01'
        source: Oberschelp, Christopher, et al. "Global emission hotspots of coal power
          generation."; IPCC 2014
        value: 817.319095
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 859.37
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 522.3363922999999
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 521.0899999999999
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 524.39
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 480.09
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 496.29
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 471.72
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 459.53
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 414.66
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 381.33
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 388.46
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 357.41
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 301.11
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 36.5
    unknown:
      _url: https://github.com/electricitymaps/electricitymaps-contrib/issues/3015#issuecomment-888154930
      source: Electricity Maps, 2020 average. See disclaimer
      value: 342
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
estimation_method: RECONSTRUCT_BREAKDOWN
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.023504727838821585
        coal: 0.260849511137503
        gas: 0.23162716587852436
        geothermal: 4.174416927459995e-05
        hydro: 0.052004098647775575
        hydro discharge: 0.002489857025228999
        nuclear: 0.06765508415590223
        oil: 0.0006671760796863028
        solar: 0.013314183782546838
        unknown: 0.30518069870201564
        wind: 0.042665739438717286
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.020066962191209885
        coal: 0.2895318999761416
        gas: 0.271483904229351
        geothermal: 3.67963115037262e-05
        hydro: 0.03626464462221321
        hydro discharge: 0.001741945189944852
        nuclear: 0.056911561078219784
        oil: 0.0003994579250406276
        solar: 0.02220679422296801
        unknown: 0.26543238395471785
        wind: 0.03592364544585461
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.018176472649841704
        coal: 0.24598659329367978
        gas: 0.29392874224516585
        geothermal: 3.294526371936428e-05
        hydro: 0.039317633390621935
        hydro discharge: 0.001538974582027345
        nuclear: 0.04779976961154324
        oil: 0.0004052637743681047
        solar: 0.025725814782940806
        unknown: 0.2717718875733103
        wind: 0.05531589560471488
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.02277701756987892
        coal: 0.2364661811319581
        gas: 0.29249069935943806
        geothermal: 4.500195507586085e-05
        hydro: 0.03310708132074495
        hydro discharge: 0.002397558612560101
        nuclear: 0.052923237102526395
        oil: 0.0007377337058747215
        solar: 0.03989201402737403
        unknown: 0.24474966141414012
        wind: 0.07441380188960008
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.026307048597304653
        coal: 0.14846792428699224
        gas: 0.37194038126658
        geothermal: 2.5112157196234856e-05
        hydro: 0.020936549656377132
        hydro discharge: 0.0012917161802815586
        nuclear: 0.06053180185105726
        oil: 0.0005650208021408723
        solar: 0.052130788170166115
        unknown: 0.23575352875950695
        wind: 0.08205012398791693
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03286378907894234
        coal: 0.10703022238262472
        gas: 0.41473078853450074
        geothermal: 1.906748244501869e-05
        hydro: 0.038738933202960735
        hydro discharge: 0.001968534972672668
        nuclear: 0.04674858379619387
        oil: 0.0004132573653313014
        solar: 0.07462368802047761
        unknown: 0.17301318915676167
        wind: 0.10984994482718766
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.034942365974229526
        coal: 0.18133608707159238
        gas: 0.3344912268430079
        geothermal: 1.9357367119694865e-05
        hydro: 0.03160294095153997
        hydro discharge: 0.0033151333712918593
        nuclear: 0.05246929588004117
        oil: 0.0003962300232863966
        solar: 0.10132094433370065
        unknown: 0.12936451738004875
        wind: 0.13074188272418263
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.03210894834879892
        coal: 0.1541517581055266
        gas: 0.2784457207118214
        geothermal: 1.2755220058374555e-05
        hydro: 0.014982537736947696
        hydro discharge: 0.0012041517069040796
        nuclear: 0.04387625073633541
        oil: 0.00024315894519206607
        solar: 0.13845552827406854
        unknown: 0.1966553275611019
        wind: 0.13986385598122147
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 2.374626751382345e-09
        biomass: 0.03255042273396558
        coal: 0.10891712963609579
        gas: 0.26265749698036983
        geothermal: 1.7127612847300523e-05
        hydro: 0.026955354728028815
        hydro discharge: 0.0014943378919590512
        nuclear: 0.04390350401877278
        oil: 0.0003331844493968771
        solar: 0.1681621254932683
        unknown: 0.15530246017637503
        wind: 0.19970684592554816
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: NORDPOOL.fetch_price
  production: NED.fetch_production
  productionCapacity: ENTSOE.fetch_production_capacity
  productionPerModeForecast: NED.fetch_production_forecast
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Amsterdam
