bounding_box:
  - - 51.47861495000012
    - 16.142401434000078
  - - 60.34457441500007
    - 26.885972398000035
capacity:
  gas:
    - datetime: '2020-01-01'
      source: Climatescope
      value: 10544
    - datetime: '2021-01-01'
      source: Climatescope
      value: 9764
    - datetime: '2022-01-01'
      source: Climatescope
      value: 9495
    - datetime: '2023-01-01'
      source: Climatescope
      value: 9044
  oil:
    - datetime: '2020-01-01'
      source: Climatescope
      value: 150
  solar:
    - datetime: '2020-01-01'
      source: Climatescope
      value: 43
    - datetime: '2021-01-01'
      source: Climatescope
      value: 329
    - datetime: '2022-01-01'
      source: Climatescope
      value: 924
    - datetime: '2023-01-01'
      source: Climatescope
      value: 1224
  wind:
    - datetime: '2020-01-01'
      source: Climatescope
      value: 49
contributors:
  - q--
  - nessie2013
  - florianscheidl
country: OM
emissionFactors:
  lifecycle:
    battery discharge:
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 700.0
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 471.25
    hydro discharge:
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 700.0
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 471.25
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 0.9999999975198319
        wind: 0.0
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.9241263713007266
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.020394883822319847
        solar: 0.05139963425427532
        unknown: 0.004078967295063173
        wind: 0.0
parsers:
  consumption: GCCIA.fetch_consumption
region: Asia
sources:
  Climatescope:
    link: https://www.global-climatescope.org/markets/om/
timezone: Asia/Muscat
