_comment: Biomass includes 19.227 MW of biogas and 6.03 MW of waste incineration
bounding_box:
  - - 20.2201924985
    - 43.6884447292
  - - 29.62654341
    - 48.2208812526
capacity:
  biomass:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 118.0
  coal:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 2673.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 1909.0
  gas:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1988.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 2238.0
  hydro:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 6136.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 6139.0
  nuclear:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1300.0
  solar:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 1185.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 1293.0
  wind:
    - datetime: '2023-01-01'
      source: entsoe.eu
      value: 2957.0
    - datetime: '2024-01-01'
      source: entsoe.eu
      value: 2958.0
contributors:
  - corradio
  - mzaharie
country: RO
delays:
  production: 6
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 268.5393808214638
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 544.7045496818258
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 579.95780365539
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 540.1635135660792
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 502.57187053189597
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 437.35043659159794
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 460.80145690263157
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 1169.308063
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1085.6
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 1224.26
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 687.5901733
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 568.48
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 567.48
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 268.5393808214638
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 544.7045496818258
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 579.95780365539
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 540.1635135660792
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 502.57187053189597
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 437.35043659159794
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 460.80145690263157
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 641.08
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 480.47
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 462.06
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 486.1
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 456.23
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 429.12
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 371.99
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 390.9
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 371.55
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 297.65
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1259.7512649999999
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1176.0432019999998
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 1284.26
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 807.5901733
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 688.48
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 687.48
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 480.47
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 462.06
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 486.1
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 456.23
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 429.12
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 371.99
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 390.9
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 371.55
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 297.65
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 885.08
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 29.78
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.008343004654539637
        coal: 0.28259947355011633
        gas: 0.14521389124044334
        geothermal: 2.097521317109146e-09
        hydro: 0.26406067699178526
        hydro discharge: 3.620146999887294e-05
        nuclear: 0.17983065189704023
        oil: 9.467337258215224e-06
        solar: 0.019114259047798038
        unknown: 0.0001730720772648546
        wind: 0.10061930400606996
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.007118263077933529
        coal: 0.26778204770859715
        gas: 0.15099766120006777
        geothermal: 2.9723386552215157e-07
        hydro: 0.2754458659234173
        hydro discharge: 0.0003275050271993969
        nuclear: 0.18024869935429486
        oil: 2.8169085990147912e-05
        solar: 0.01876467588804454
        unknown: 0.0007186219169696636
        wind: 0.09856905585252346
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.00682602116281003
        coal: 0.27681125700680426
        gas: 0.1665376019495329
        geothermal: 7.164406141660658e-07
        hydro: 0.22735978681077343
        hydro discharge: 0.0003174603188442346
        nuclear: 0.19046141297932967
        oil: 3.7662174808577694e-05
        solar: 0.021585356074834867
        unknown: 0.0008452205211453613
        wind: 0.10921777836053125
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.005629087413857834
        coal: 0.25330232300045086
        gas: 0.16623132417103018
        geothermal: 1.576594874450022e-06
        hydro: 0.27428536295369027
        hydro discharge: 0.00014343179592550572
        nuclear: 0.1858182633949209
        oil: 2.1668636070353418e-05
        solar: 0.020951245590304233
        unknown: 0.0003558944617456022
        wind: 0.09325976448065565
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.007938108400755015
        coal: 0.2412412636947919
        gas: 0.15703612979230736
        geothermal: 2.777045747255677e-06
        hydro: 0.2532083565685921
        hydro discharge: 0.0005382687158548562
        nuclear: 0.21125599431947636
        oil: 0.0001129145238548562
        solar: 0.022496951307689715
        unknown: 0.0017259606071149522
        wind: 0.10444316782443165
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.009173626901281087
        coal: 0.18492474414003757
        gas: 0.17739256674490284
        geothermal: 6.534440008786866e-06
        hydro: 0.2634059853125358
        hydro discharge: 0.00089486448222405
        nuclear: 0.2267465461383858
        oil: 0.00010338845944642915
        solar: 0.023700273149435413
        unknown: 0.003302998098301919
        wind: 0.11034860205475826
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.010250447827581227
        coal: 0.19736862189487703
        gas: 0.17624972069100142
        geothermal: 7.627739345794807e-06
        hydro: 0.2806869001686203
        hydro discharge: 0.0005552746160495469
        nuclear: 0.2089638768073416
        oil: 8.137343674433928e-05
        solar: 0.022523490115461994
        unknown: 0.002743236247055437
        wind: 0.10056934464405874
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.010261034540501953
        coal: 0.20657059032557148
        gas: 0.18316002310260096
        geothermal: 8.24245252857199e-06
        hydro: 0.23821988309935627
        hydro discharge: 0.00037719640307121497
        nuclear: 0.22130932618993718
        oil: 0.00010809727201213929
        solar: 0.025471930594314674
        unknown: 0.0022864346052005836
        wind: 0.11222726247425091
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.007306907882462246
        coal: 0.15331133729471524
        gas: 0.16578010460800768
        geothermal: 1.2818057916568337e-05
        hydro: 0.3099119729146331
        hydro discharge: 0.0007371891438983204
        nuclear: 0.2121766174381314
        oil: 9.303748507370303e-05
        solar: 0.028652702435479526
        unknown: 0.0020965268184074473
        wind: 0.1199208095204838
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  production: ENTSOE.fetch_production
  productionCapacity: ENTSOE.fetch_production_capacity
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Bucharest
