bounding_box:
  - - 11.800952121030544
    - 54.84588629391277
  - - 17.699686739075773
    - 58.013078824484765
capacity:
  biomass: 883
  coal: 0
  gas: 582
  geothermal: 0
  hydro: 345
  nuclear: 0
  oil: 662
  solar: 1091
  wind: 2098
country: SE
delays:
  production: 7
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 17.232682859172968
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 34.53847131438525
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 15.97892193773949
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 31.487804845201087
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 38.91845040864397
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 6.380305856936989
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 15.369236620057007
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 1057.262766
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1075.5
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 447.9740216
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 346.62
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 312.59
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 17.232682859172968
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 34.53847131438525
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 15.97892193773949
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 31.487804845201087
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 38.91845040864397
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 6.380305856936989
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 15.369236620057007
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 373.49
    unknown:
      - _comment: Uses the 2020 (2022 edition) eurostat production values for SE for
          the sources in unknown
        datetime: '2022-01-01'
        source: Eurostat 2022; assumes 98.26% biomass, 1.09% oil, 0.64% peat, 0.01%
          coal
        value: 28.6
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 48.74008314525681
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 61.501809138964035
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 46.97
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 65.02
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 79.57
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 40.56
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 59.67
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 40.45
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 41.4
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1153.629975
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1171.867209
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 567.9740216
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 466.62
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 432.59
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 48.74008314525681
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 61.501809138964035
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 46.97
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 65.02
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 79.57
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 40.56
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 59.67
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 40.45
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 41.4
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 617.49
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 35.6
    unknown:
      - _comment: Uses the 2020 (2022 edition) eurostat production values for SE for
          the sources in unknown
        datetime: '2022-01-01'
        source: Eurostat 2022; assumes 98.26% biomass, 1.09% oil, 0.64% peat, 0.01%
          coal
        value: 258
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0029359493045969043
        coal: 0.010850929807982433
        gas: 0.006697188104233741
        geothermal: 1.9458916081204937e-06
        hydro: 0.28334478937071544
        hydro discharge: 5.2948228117312056e-05
        nuclear: 0.3216105986232798
        oil: 0.00026689722539250706
        solar: 0.013828894486485286
        unknown: 0.08831576118466927
        wind: 0.2720965358535611
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.00828100308793699
        coal: 0.011472676891100302
        gas: 0.004511803736789479
        geothermal: 3.0627665567791174e-06
        hydro: 0.29797973666549693
        hydro discharge: 0.00020475616817417278
        nuclear: 0.3014537340439085
        oil: 0.0006239290401447012
        solar: 0.014977079534259571
        unknown: 0.07876556698426672
        wind: 0.2817264268515917
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.004843256736026705
        coal: 0.006215706353379441
        gas: 0.0052354810716606125
        geothermal: 5.83767823618039e-06
        hydro: 0.3230630528536068
        hydro discharge: 0.0015980282095966589
        nuclear: 0.2865935886285758
        oil: 0.00029634876264532936
        solar: 0.017353708399439765
        unknown: 0.07581697072798588
        wind: 0.27897783862312003
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.01221690620617217
        coal: 0.025324800009161822
        gas: 0.009663752422569248
        geothermal: 5.091783143919745e-06
        hydro: 0.2793930261633247
        hydro discharge: 0.00015305657217107432
        nuclear: 0.29243973922686634
        oil: 0.0006411969216168838
        solar: 0.015900748326256597
        unknown: 0.07937976248374472
        wind: 0.2848816807317283
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.015247135689158899
        coal: 0.034163308785141636
        gas: 0.01482148164172635
        geothermal: 1.3313023823592024e-05
        hydro: 0.2633417044857041
        hydro discharge: 0.00039267278768967797
        nuclear: 0.28260669074234324
        oil: 0.0010006484557315146
        solar: 0.01801032492130584
        unknown: 0.0773773090322221
        wind: 0.2930252471749332
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.007746014636820174
        coal: 0.011617968962108765
        gas: 0.00854446015775938
        geothermal: 6.140787856835623e-06
        hydro: 0.28257399847170434
        hydro discharge: 0.0017149954923830855
        nuclear: 0.2913738727772991
        oil: 0.0005617933141792692
        solar: 0.0038300503854653283
        unknown: 0.12201190790417296
        wind: 0.27001863167505596
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.004042225954657631
        coal: 0.005984952091814134
        gas: 0.0025162032191638293
        geothermal: 2.8556064418079612e-06
        hydro: 0.3197140523672449
        hydro discharge: 0.00045814726269738024
        nuclear: 0.3021995442321449
        oil: 0.0002838381334148682
        solar: 0.013063079237471149
        unknown: 0.08505615265160521
        wind: 0.26667883304036916
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.005776065810768341
        coal: 0.008832482916417795
        gas: 0.0035208769364939736
        geothermal: 6.7719504460836485e-06
        hydro: 0.320927082140148
        hydro discharge: 0.0004992976249628575
        nuclear: 0.2713209752350139
        oil: 0.0005240532844172071
        solar: 0.022818575566277564
        unknown: 0.06868014000307567
        wind: 0.29709350570917714
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: NORDPOOL.fetch_price
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
  productionPerUnit: ENTSOE.fetch_production_per_units
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  Eurostat 2022:
    link: https://doi.org/10.2908/NRG_BAL_C
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
timezone: Europe/Stockholm
