bounding_box:
  - - 11.25
    - 55.379110448
  - - 21.2255859375
    - 69.0214140884
capacity:
  biomass: 4462
  coal: 0
  gas: 1535
  geothermal: 0
  hydro: 16334
  nuclear: 6871
  oil: 662
  solar: 2385
  wind: 14662
contributors:
  - augustekman
  - RRyyas
  - corradio
  - VIKTORVAV99
  - dpkruczek
country: SE
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 37.49355055236267
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 58.11599195696885
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 47.6194051539446
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 51.29108253743617
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 52.79918134183244
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 40.05161032322605
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 47.31267597911351
    biomass:
      datetime: '2021-01-01'
      source: BEIS 2021
      value: 0.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 1057.262766
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 1075.5
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 447.9740216
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 346.62
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 312.59
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 37.49355055236267
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 58.11599195696885
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 47.6194051539446
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 51.29108253743617
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 52.79918134183244
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 40.05161032322605
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 47.31267597911351
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021
        value: 880.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022
        value: 925.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023
        value: 373.49
    unknown:
      - _comment: Uses the 2015 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2015-01-01'
        source: Eurostat 2022; assumes 85.46% biomass, 7.98% gas, 2.77% coal, 1.8% oil,
          1.3% peat, 0.69% solar
        value: 67.7
      - _comment: Uses the 2016 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2016-01-01'
        source: Eurostat 2022; assumes 85.52% biomass, 7.84% gas, 2.6% oil, 1.74% coal,
          1.38% peat, 0.94% solar
        value: 63.1
      - _comment: Uses the 2016 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2017-01-01'
        source: Eurostat 2022; assumes 87.2% biomass, 6.21% gas, 2.04% coal, 1.84% oil,
          1.46% solar, 1.26% peat
        value: 55.5
      - _comment: Uses the 2018 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2018-01-01'
        source: Eurostat 2022; assumes 84.38% biomass, 7.15% gas, 2.55% solar, 2.10%
          coal, 1.92% oil, 1.90% peat
        value: 64.6
      - _comment: Uses the 2019 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2019-01-01'
        source: Eurostat 2022; assumes 86.15% biomass, 6.15% gas, 3.98% solar, 1.27%
          oil, 1.24% coal, 1.20% peat
        value: 46.5
      - _comment: Uses the 2020 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2020-01-01'
        source: Eurostat 2022; assumes 86.72% biomass, 7.17% solar, 4.58% gas, 0.96%
          oil, 0.56% peat, 0.01% coal
        value: 27.4
      - _comment: Uses the 2020 values with 2021 emission factors
        datetime: '2021-01-01'
        source: Eurostat 2022; assumes 86.72% biomass, 7.17% solar, 4.58% gas, 0.96%
          oil, 0.56% peat, 0.01% coal
        value: 35.5
      - _comment: Uses the 2020 values with 2022 emission factors minus solar and gas
        datetime: '2022-01-01'
        source: Eurostat 2022; assumes 98.26% biomass, 1.09% oil, 0.64% peat, 0.01%
          coal
        value: 28.6
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 37.90998676195598
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 55.5151467459363
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 27.97
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 31.85
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 33.73
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 24.83
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 31.74
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 25.82
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 25.01
    biomass:
      datetime: '2014-01-01'
      source: BEIS 2021; IPCC 2014
      value: 230.0
    coal:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1153.629975
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; Oberschelp, Christopher, et al. "Global emission
          hotspots of coal power generation."
        value: 1171.867209
    gas:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 567.9740216
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 466.62
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 432.59
    hydro:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 10.7
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 37.90998676195598
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 55.5151467459363
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 27.97
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 31.85
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 33.73
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 24.83
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 31.74
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 25.82
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 25.01
    nuclear:
      datetime: '2020-01-01'
      source: UNECE 2022
      value: 5.13
    oil:
      - datetime: '2021-01-01'
        source: EU-ETS, ENTSO-E 2021; IPCC 2014
        value: 1124.903938
      - datetime: '2022-01-01'
        source: EU-ETS, ENTSO-E 2022; IPCC 2014
        value: 1169.95
      - datetime: '2023-01-01'
        source: EU-ETS, ENTSO-E 2023; IPCC 2014
        value: 617.49
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 40.81666667
    unknown:
      - _comment: Uses the 2015 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2015-01-01'
        source: assumes 85.46% biomass, 7.98% gas, 2.77% coal, 1.8% oil, 1.3% peat,
          0.69% solar
        value: 281
      - _comment: Uses the 2016 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2016-01-01'
        source: assumes 85.52% biomass, 7.84% gas, 2.6% oil, 1.74% coal, 1.38% peat,
          0.94% solar
        value: 277.9
      - _comment: Uses the 2016 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2017-01-01'
        source: assumes 87.2% biomass, 6.21% gas, 2.04% coal, 1.84% oil, 1.46% solar,
          1.26% peat
        value: 270.6
      - _comment: Uses the 2018 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2018-01-01'
        source: assumes 84.38% biomass, 7.15% gas, 2.55% solar, 2.10% coal, 1.92% oil,
          1.90% peat
        value: 275.5
      - _comment: Uses the 2019 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2019-01-01'
        source: assumes 86.15% biomass, 6.15% gas, 3.98% solar, 1.27% oil, 1.24% coal,
          1.20% peat
        value: 258.4
      - _comment: Uses the 2020 (2022 edition) eurostat production values for the sources
          in unknown
        datetime: '2020-01-01'
        source: assumes 86.72% biomass, 7.17% solar, 4.58% gas, 0.96% oil, 0.56% peat,
          0.01% coal
        value: 237.9
      - _comment: Uses the 2020 values with 2021 emission factors
        datetime: '2021-01-01'
        source: assumes 86.72% biomass, 7.17% solar, 4.58% gas, 0.96% oil, 0.56% peat,
          0.01% coal
        value: 245.8
      - _comment: Uses the 2020 values with 2022 emission factors minus solar and gas
        datetime: '2022-01-01'
        source: assumes 98.26% biomass, 1.09% oil, 0.64% peat, 0.01% coal
        value: 258
    wind:
      datetime: '2021-01-01'
      source: UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the
        outlook for 2022-2026" Wind Europe Proceedings (2021)
      value: 12.62
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0008544602403404806
        coal: 0.0030533526706254975
        gas: 0.001922495681605918
        geothermal: 6.442205900022875e-07
        hydro: 0.5157980032770925
        hydro discharge: 3.912496156542762e-05
        nuclear: 0.31448953696475124
        oil: 7.529063423769025e-05
        solar: 0.0004042073266118967
        unknown: 0.05985935476591089
        wind: 0.10350350094651478
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0025066285548356547
        coal: 0.0035298517558361936
        gas: 0.002682784783063185
        geothermal: 1.0208897289188394e-06
        hydro: 0.44498989868684746
        hydro discharge: 5.419549722112062e-05
        nuclear: 0.2856675651124963
        oil: 0.0002900395611749182
        solar: 0.005846361563466728
        unknown: 0.046981438421167886
        wind: 0.2074501963619513
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0032726948395021844
        coal: 0.006765634303280902
        gas: 0.003724782113534383
        geothermal: 1.4950673676325009e-06
        hydro: 0.4393254442688722
        hydro discharge: 4.121946433312034e-05
        nuclear: 0.28550015754869407
        oil: 0.00014408037411796107
        solar: 0.006043124288054485
        unknown: 0.04723620643768159
        wind: 0.20794513923450028
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0037420201074876472
        coal: 0.007913512135534043
        gas: 0.0045020358752159775
        geothermal: 3.0502551454092127e-06
        hydro: 0.43130356193754993
        hydro discharge: 8.456712273200982e-05
        nuclear: 0.2850821580657975
        oil: 0.0002392857459013021
        solar: 0.0064999742526070416
        unknown: 0.047291204622185834
        wind: 0.21333860301721452
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.001493432500850227
        coal: 0.002015781636145986
        gas: 0.002194468284561183
        geothermal: 1.454053364117847e-06
        hydro: 0.44621860824223136
        hydro discharge: 0.0012403217408877157
        nuclear: 0.2906045189285992
        oil: 8.219967876268834e-05
        solar: 0.006507794375026403
        unknown: 0.046613061255313976
        wind: 0.20302833989811478
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.001702280490704727
        coal: 0.0026844745756711115
        gas: 0.00208823768223315
        geothermal: 1.2764335480732532e-06
        hydro: 0.41680106874631706
        hydro discharge: 0.001108855599794965
        nuclear: 0.2927358847314054
        oil: 0.00010626993802001468
        solar: 0.0009274449391962091
        unknown: 0.0705066614375738
        wind: 0.2113375219649589
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0012849833741771296
        coal: 0.001968094173946284
        gas: 0.0014370040644001761
        geothermal: 8.481823075837515e-07
        hydro: 0.4431591327887025
        hydro discharge: 0.00030687772073256195
        nuclear: 0.30052667125456645
        oil: 7.07557333260159e-05
        solar: 0.005178336223152104
        unknown: 0.05074580595317665
        wind: 0.19532146955036517
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.001934774600483335
        coal: 0.0024011747361055986
        gas: 0.0016585650882186085
        geothermal: 1.7220316261973122e-06
        hydro: 0.43490580121667605
        hydro discharge: 0.000330513605173766
        nuclear: 0.2920784879137254
        oil: 0.00012547109330606946
        solar: 0.008883443915798284
        unknown: 0.04401025006882799
        wind: 0.21366977202437476
isLowCarbon:
  unknown:
    - _comment: Sum of renewable sources in SE unknown production for 2015
      datetime: '2015-01-01'
      value: 0.8615
    - _comment: Sum of renewable sources in SE unknown production for 2016
      datetime: '2016-01-01'
      value: 0.8646
    - _comment: Sum of renewable sources in SE unknown production for 2017
      datetime: '2017-01-01'
      value: 0.8866
    - _comment: Sum of renewable sources in SE unknown production for 2018
      datetime: '2018-01-01'
      value: 0.8693
    - _comment: Sum of renewable sources in SE unknown production for 2019
      datetime: '2019-01-01'
      value: 0.9013
    - _comment: Sum of renewable sources in SE unknown production for 2020
      datetime: '2020-01-01'
      value: 0.9332
    - _comment: Sum of renewable sources in SE unknown production for 2022
      datetime: '2022-01-01'
      value: 0.9826
isRenewable:
  unknown:
    - _comment: Sum of renewable sources in SE unknown production for 2015
      datetime: '2015-01-01'
      value: 0.8615
    - _comment: Sum of renewable sources in SE unknown production for 2016
      datetime: '2016-01-01'
      value: 0.8646
    - _comment: Sum of renewable sources in SE unknown production for 2017
      datetime: '2017-01-01'
      value: 0.8866
    - _comment: Sum of renewable sources in SE unknown production for 2018
      datetime: '2018-01-01'
      value: 0.8693
    - _comment: Sum of renewable sources in SE unknown production for 2019
      datetime: '2019-01-01'
      value: 0.9013
    - _comment: Sum of renewable sources in SE unknown production for 2020
      datetime: '2020-01-01'
      value: 0.9332
    - _comment: Sum of renewable sources in SE unknown production for 2022
      datetime: '2022-01-01'
      value: 0.9826
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  production: ENTSOE.fetch_production
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
region: Europe
sources:
  EU-ETS, ENTSO-E 2021:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2022:
    link: https://drive.google.com/file/d/15UeUHyhcjVw8fGLc0Zx_HELSx20cw_-e/view?usp=share_link
  EU-ETS, ENTSO-E 2023:
    link: https://colab.research.google.com/drive/1IkDXX4p1xQIuY3WicL94TUkRcZQnS9c7?usp=drive_link
  Eurostat 2022:
    link: https://doi.org/10.2908/NRG_BAL_C
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  UNECE 2022:
    link: https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf
  ? UNECE 2022, WindEurope "Wind energy in Europe, 2021 Statistics and the outlook
    for 2022-2026" Wind Europe Proceedings (2021)
  : link:
      https://unece.org/sites/default/files/2022-04/LCA_3_FINAL%20March%202022.pdf#page=37,
      https://proceedings.windeurope.org/biplatform/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSWhORFJ0ZDJJMWVUbG9OMll6TVRaaGEza3lkamgxZG1aM056WnZZZ1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpQVk1cGJteHBibVU3SUdacGJHVnVZVzFsUFNKWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtSWpzZ1ptbHNaVzVoYldVcVBWVlVSaTA0SnlkWGFXNWtaWFZ5YjNCbExWZHBibVF0Wlc1bGNtZDVMV2x1TFVWMWNtOXdaUzB5TURJeExYTjBZWFJwYzNScFkzTXVjR1JtQmpzR1ZEb1JZMjl1ZEdWdWRGOTBlWEJsU1NJVVlYQndiR2xqWVhScGIyNHZjR1JtQmpzR1ZBPT0iLCJleHAiOiIyMDIyLTExLTAyVDE1OjU0OjAzLjEyNFoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--c25280a7345257bd91bfaf6d64ddb75c55eef799/Windeurope-Wind-energy-in-Europe-2021-statistics.pdf?content_type=application%2Fpdf&disposition=inline%3B+filename%3D%22Windeurope-Wind-energy-in-Europe-2021-statistics.pdf%22%3B+filename%2A%3DUTF-8%27%27Windeurope-Wind-energy-in-Europe-2021-statistics.pdf
subZoneNames:
  - SE-SE1
  - SE-SE2
  - SE-SE3
  - SE-SE4
timezone: Europe/Stockholm
