bounding_box:
  - - -83.14555
    - 31.584470000000103
  - - -78.92575821
    - 35.2360579840001
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 4.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 120.0
    - datetime: '2024-01-01'
      source: EIA.gov
      value: 20.8
    - datetime: '2024-06-01'
      source: EIA.gov
      value: 130.4
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1431.5
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 3510.5
    - datetime: '2024-06-01'
      source: EIA.gov
      value: 3400.9
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 241.8
    - datetime: '2024-06-01'
      source: EIA.gov
      value: 244.3
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 587.2
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1029.6
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 56.7
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 978.1
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
comment: South Carolina Electric & Gas Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 35
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available. A third of the nuclear-related electricity production
  is attributed to the balancing authority South Carolina Public Service Authority
  (US-CAR-SC) due to an agreement between the two balancing authorities. Read more
  on the zone definition wiki page.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 333.45584889389426
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 369.387291702775
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 371.6960890227183
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 461.7475641490103
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 384.8941791840858
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 341.0146565361128
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 359.73740517000465
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 0.0
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 0.0
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 849.2213607
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 885.72
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 407.4177138
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 462.31
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 333.45584889389426
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 369.387291702775
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 371.6960890227183
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 461.7475641490103
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 384.8941791840858
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 341.0146565361128
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 359.73740517000465
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 411.5952943203473
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 450.76705463366125
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 445.81
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 546.65
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 467.12
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 423.61
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 474.64
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 445.47
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 452.35
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 90.54773858
      - datetime: '2021-01-01'
        source: eGrid 2021; eGrid 2021
        value: 277.252
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 932.0702837
      - datetime: '2021-01-01'
        source: eGrid 2021; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 968.568923
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 527.4177138
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 582.31
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 411.5952943203473
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 450.76705463366125
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 445.81
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 546.65
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 467.12
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 423.61
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 474.64
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 445.47
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 452.35
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.1919388365611012
        gas: 0.5025520570687312
        geothermal: 0.0
        hydro: 0.0317146224119546
        hydro discharge: 0.0
        nuclear: 0.21190851534364152
        oil: 0.0
        solar: 0.05903604640979591
        unknown: 0.0028507321355780903
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.19193927472676642
        gas: 0.5025532043146995
        geothermal: 0.0
        hydro: 0.03171469481136514
        hydro discharge: 0.0
        nuclear: 0.21190899909688946
        oil: 0.0
        solar: 0.059033898197732804
        unknown: 0.0028507386433436104
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.18742516229405587
        gas: 0.49974421865653124
        geothermal: 0.0
        hydro: 0.03431078070799077
        hydro discharge: 0.000380855078564775
        nuclear: 0.2176132311411495
        oil: 2.151520173614745e-05
        solar: 0.05696093483259734
        unknown: 0.003498408018270314
        wind: 4.4861599611161344e-05
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.3214304947216419
        gas: 0.4399486453590058
        geothermal: 0.0
        hydro: 0.0405005506681862
        hydro discharge: 0.0011176110030240165
        nuclear: 0.16454727632964256
        oil: 1.4847165557749801e-05
        solar: 0.016467489685652602
        unknown: 0.015941783027489508
        wind: 3.108518419880289e-05
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.21533149102084395
        gas: 0.4937266204457581
        geothermal: 0.0
        hydro: 0.037827775732831546
        hydro discharge: 0.000280317847523117
        nuclear: 0.22166585463183658
        oil: 6.475879755062101e-06
        solar: 0.02922540815921918
        unknown: 0.0019044186201371907
        wind: 3.126251016973406e-05
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.15343316901527523
        gas: 0.5184664932583573
        geothermal: 0.0
        hydro: 0.045628812123294074
        hydro discharge: 0.00023031537440515164
        nuclear: 0.2196998129483287
        oil: 4.7436759900481635e-06
        solar: 0.05984918243374145
        unknown: 0.002650167208387969
        wind: 3.6834008845103896e-05
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.1744133673194287
        gas: 0.5251430302376525
        geothermal: 0.0
        hydro: 0.03296857686331639
        hydro discharge: 0.0002873837620064509
        nuclear: 0.19549786525377738
        oil: 5.823383367184787e-06
        solar: 0.06892130831136678
        unknown: 0.002688234625230407
        wind: 7.374835449605523e-05
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 4.643887201818847e-10
        coal: 0.15682706889899994
        gas: 0.5050222544130291
        geothermal: 0.0
        hydro: 0.033411634379831925
        hydro discharge: 1.6654372671882933e-05
        nuclear: 0.23053908875722756
        oil: 3.474927915377007e-05
        solar: 0.07094943776945255
        unknown: 0.0030516826426370764
        wind: 0.00014684575037487432
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.16017571777897244
        gas: 0.5133093460904063
        geothermal: 0.0
        hydro: 0.032589510651999
        hydro discharge: 1.2069656847530967e-05
        nuclear: 0.21625282181492964
        oil: 5.373384499600865e-06
        solar: 0.07498581263310113
        unknown: 0.002574351858337794
        wind: 9.441022523431366e-05
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Eastern
