bounding_box:
  - - -98.122757
    - 34.320635
  - - -89.033722
    - 40.781817
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 261.0
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 32.8
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1327.6
    - datetime: '2024-01-01'
      source: EIA.gov
      value: 1253.2
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 161.4
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 17.0
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 18.5
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 499.0
comment: Southwestern Power Administration
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 36
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 128.73370000980418
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 128.73370000980415
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 136.07774539875038
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 236.62726623997656
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 110.4479089107277
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 132.5004986598673
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 164.00004434072346
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 987.9224617
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 1062.02
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 128.73370000980418
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 128.73370000980415
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 136.07774539875038
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 236.62726623997656
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 110.4479089107277
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 132.5004986598673
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 164.00004434072346
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 175.34791543743
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 175.34791543743
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 175.59
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 295.46
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 152.94
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 178.71
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 210.23
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 222.96
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 195.85
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 1047.9224617
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 1122.02
    gas:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 490.0
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 175.34791543743
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 175.34791543743
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 175.59
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 295.46
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 152.94
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 178.71
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 210.23
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 222.96
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 195.85
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.7761125520290202
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 0.2238874479709796
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.0
        geothermal: 0.0
        hydro: 0.7761125520290203
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 0.2238874479709796
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 9.454247536579133e-06
        coal: 0.009265333276382938
        gas: 0.003329349014612576
        geothermal: 0.0
        hydro: 0.7694466491971933
        hydro discharge: 0.0
        nuclear: 0.0017661128803017762
        oil: 2.706750266473027e-05
        solar: 2.1364430658807434e-05
        unknown: 0.20767054349051262
        wind: 0.008465842906110384
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.000964381928596424
        gas: 0.0004831620770427274
        geothermal: 0.0
        hydro: 0.8094005220568167
        hydro discharge: 0.0
        nuclear: 2.3156015959735656e-05
        oil: 0.0
        solar: 2.0091987817558054e-07
        unknown: 0.1889945801862862
        wind: 0.00013376240889539275
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 4.426582364864741e-07
        coal: 0.003915367434002424
        gas: 0.001984399985982489
        geothermal: 0.0
        hydro: 0.7693716650774006
        hydro discharge: 0.0
        nuclear: 0.0003525772853614765
        oil: 8.668723797860118e-07
        solar: 6.400100335866937e-06
        unknown: 0.2216211251265726
        wind: 0.002744001519793278
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 4.0790974069919437e-07
        coal: 0.011688560912976166
        gas: 0.0026363021127870437
        geothermal: 0.0
        hydro: 0.7225290403923349
        hydro discharge: 0.0
        nuclear: 0.00047601212604410993
        oil: 2.2249622219956056e-07
        solar: 8.287984276933633e-06
        unknown: 0.2570147125626929
        wind: 0.005642949187425255
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.9622047908100436e-05
        coal: 0.03963559329867641
        gas: 0.017052592962653042
        geothermal: 0.0
        hydro: 0.593845937226901
        hydro discharge: 7.862297387332744e-08
        nuclear: 0.003731468803734941
        oil: 4.9611096514069614e-05
        solar: 9.913233820085541e-05
        unknown: 0.3296001984713425
        wind: 0.015963642310800635
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 3.756466021294917e-06
        coal: 0.021574296256033753
        gas: 0.009879042882945034
        geothermal: 0.0
        hydro: 0.6932108763519466
        hydro discharge: 0.0
        nuclear: 0.001734602626869468
        oil: 4.8180759838347835e-06
        solar: 5.260413468226396e-05
        unknown: 0.2554041935662299
        wind: 0.01813172652404726
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 3.2640286161412924e-05
        coal: 0.03670392726730754
        gas: 0.031857416101547555
        geothermal: 0.0
        hydro: 0.704763842313138
        hydro discharge: 0.0
        nuclear: 0.007008073130138858
        oil: 9.265469359366072e-06
        solar: 0.00019298507091934322
        unknown: 0.1757453610552202
        wind: 0.04367690091164269
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Central
