bounding_box:
  - - -82.8222040759999
    - 31.5821888830001
  - - -78.04086
    - 35.334748543
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 218.4
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 3650.1
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1102.0
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 231.2
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 229.4
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 248.2
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 303.2
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
comment: South Carolina Public Service Authority
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 37
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available. This zone includes a third of the nuclear related electricity
  production from the balancing authority South Carolina Electric & Gas Company. Read
  more on the zone definition wiki page.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 513.6256203968906
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 694.8942986729398
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 569.025494408865
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 645.7675225168629
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 543.5526226613099
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 516.0385233433849
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 565.7753046389483
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 0.0
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 0.0
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 1072.534134
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 1060.56
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 442.9124649
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 445.8
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 513.6256203968906
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 694.8942986729398
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 569.025494408865
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 645.7675225168629
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 543.5526226613099
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 516.0385233433849
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 565.7753046389483
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 585.32108045932
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 783.3566963513733
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 669.24
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 763.03
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 600.88
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 613.36
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 582.67
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 606.09
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 644.58
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 53.68073353
      - datetime: '2021-01-01'
        source: eGrid 2021; eGrid 2021
        value: 277.252
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 1165.692392
      - datetime: '2021-01-01'
        source: eGrid 2021; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 1153.7182579999999
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 562.9124649
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 565.8
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 585.32108045932
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 783.3566963513733
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 669.24
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 763.03
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 600.88
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 613.36
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 582.67
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 606.09
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 644.58
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.5123968793276095
        gas: 0.28780087700811385
        geothermal: 0.0
        hydro: 0.030624512227502457
        hydro discharge: 0.0005420658206571039
        nuclear: 0.13412876666339377
        oil: 0.00035747561907404767
        solar: 0.00405432692816917
        unknown: 0.03009453495435027
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.5123970056468568
        gas: 0.28780094795856576
        geothermal: 0.0
        hydro: 0.030624519777246593
        hydro discharge: 0.0005420659542905221
        nuclear: 0.13412879972964678
        oil: 0.00035747570720114785
        solar: 0.004054080838434433
        unknown: 0.03009454237344113
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.3941210466696241
        gas: 0.32718005685111595
        geothermal: 0.0
        hydro: 0.03782555529613638
        hydro discharge: 0.003616738193910148
        nuclear: 0.18360164617109356
        oil: 0.00012463126116092144
        solar: 0.021772687913135143
        unknown: 0.03170692346664768
        wind: 5.0501671118124205e-05
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.4759751453155882
        gas: 0.30726756864546406
        geothermal: 0.0
        hydro: 0.04134020338990413
        hydro discharge: 0.0011670142971522053
        nuclear: 0.1383853769030265
        oil: 3.613435775396149e-05
        solar: 0.00608191700485543
        unknown: 0.029706187674722783
        wind: 4.016874952590177e-05
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.3674453255360816
        gas: 0.343336097480278
        geothermal: 0.0
        hydro: 0.04554447358294803
        hydro discharge: 0.00013170643479699267
        nuclear: 0.19693586858395185
        oil: 3.8354472186262874e-05
        solar: 0.013288132161356369
        unknown: 0.033173272311972944
        wind: 0.00010647592312994358
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.3352997414077125
        gas: 0.3503644012292926
        geothermal: 0.0
        hydro: 0.05910536995543057
        hydro discharge: 0.00015983514823290714
        nuclear: 0.20159201058834708
        oil: 5.112400523197249e-05
        solar: 0.020421293540130094
        unknown: 0.032803667365924646
        wind: 0.000202250962392441
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.39242801475017597
        gas: 0.33347958929957283
        geothermal: 0.0
        hydro: 0.04285653254490887
        hydro discharge: 0.0001890917728915263
        nuclear: 0.1785536117171571
        oil: 6.456549058519069e-05
        solar: 0.02595755082820558
        unknown: 0.026273172113369814
        wind: 0.00019455624238897743
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 3.5426752085086395e-10
        coal: 0.35446022714870346
        gas: 0.36100111550375313
        geothermal: 0.0
        hydro: 0.03567975223510204
        hydro discharge: 7.193720851645558e-05
        nuclear: 0.1939663569119033
        oil: 0.0002686757792782535
        solar: 0.02973431354069071
        unknown: 0.024608188633216132
        wind: 0.00020720646746789925
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.3778103632337016
        gas: 0.3515227375655709
        geothermal: 0.0
        hydro: 0.033906064056734096
        hydro discharge: 4.7276295086318376e-05
        nuclear: 0.17797514404029938
        oil: 2.7502982155745962e-05
        solar: 0.03617072286269776
        unknown: 0.02243707426127261
        wind: 0.00010114257860738003
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Eastern
