bounding_box:
  - - -83.03593
    - 24.044093
  - - -79.53074
    - 30.69435
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 929.0
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 2502.9
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 93.8
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 87.8
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 166.9
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
comment: Florida Municipal Power Pool
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 35
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 463.8638531590523
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 519.3433928611411
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 519.3431855426442
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 532.8079191681607
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 510.5175697626441
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 515.8642003114278
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 490.1531912006671
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 768.4856555
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 806.7
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 446.015972
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 439.9
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 463.8638531590523
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 519.3433928611411
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 519.3431855426442
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 532.8079191681607
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 510.5175697626441
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 515.8642003114278
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 490.1531912006671
    oil:
      datetime: '2021-01-01'
      source: eGrid 2021
      value: 791.37
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 561.0881002838488
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 609.5529341397407
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 601.03
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 624.41
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 601.0
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 588.13
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 586.34
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 567.62
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 548.6
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 828.4856555
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 866.7
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 566.0159719999999
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 559.9
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 561.0881002838488
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 609.5529341397407
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 601.03
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 624.41
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 601.0
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 588.13
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 586.34
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 567.62
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 548.6
    oil:
      - datetime: '2014-01-01'
        source: IPCC 2014; EIA 2020/BEIS 2021
        value: 650.0
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 1035.37
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.29949770253984176
        gas: 0.607216900507734
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.05601559540906811
        oil: 0.017035436173037325
        solar: 0.012130367481323326
        unknown: 0.00810344359367948
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.29949782223725796
        gas: 0.6072171431883738
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.05601561779629172
        oil: 0.0170354429814291
        solar: 0.012129973097258556
        unknown: 0.008103446832306195
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.28110972850446125
        gas: 0.6370483782400321
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.057990335975771676
        oil: 0.0002909169673532218
        solar: 0.01456944300610533
        unknown: 0.008991606760136174
        wind: 0.0
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.36406985733242325
        gas: 0.5553053579882467
        geothermal: 0.0
        hydro: 0.00025232350083447317
        hydro discharge: 2.2126004350242253e-06
        nuclear: 0.06367866069743734
        oil: 0.0001055251293978659
        solar: 0.003662136780625228
        unknown: 0.012923461889477154
        wind: 4.398681948732371e-07
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.2973873020049896
        gas: 0.6008542129282353
        geothermal: 0.0
        hydro: 0.0001900232995418578
        hydro discharge: 9.826850892867028e-07
        nuclear: 0.07011711930380267
        oil: 0.0001654388143394521
        solar: 0.0068234572960187674
        unknown: 0.02446071447559008
        wind: 2.6988844047646196e-07
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.9575489273050794e-08
        coal: 0.25982753741146986
        gas: 0.6265177440327838
        geothermal: 0.0
        hydro: 0.00020326740621381134
        hydro discharge: 7.12547809539049e-07
        nuclear: 0.07318602266082576
        oil: 0.00026157272136374636
        solar: 0.01208258371840269
        unknown: 0.02792010367188068
        wind: 2.0022929027863388e-07
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.26424823031900224
        gas: 0.6096646350539112
        geothermal: 0.0
        hydro: 0.00013987648348954388
        hydro discharge: 7.600763469056302e-07
        nuclear: 0.06915383146333028
        oil: 0.0002208703065695987
        solar: 0.02721469174499083
        unknown: 0.02935624160030819
        wind: 4.2025819612924696e-07
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.5211848001346648e-07
        coal: 0.20428086649088084
        gas: 0.6692664656078464
        geothermal: 3.2024943160729786e-09
        hydro: 0.00011391379032082123
        hydro discharge: 3.7362433687518084e-08
        nuclear: 0.06729668874764258
        oil: 0.0003672695206539867
        solar: 0.028293106957905944
        unknown: 0.03037985438925531
        wind: 1.3226301525381403e-06
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.16628417065906728
        gas: 0.6873992287067071
        geothermal: 0.0
        hydro: 0.0001861549611646841
        hydro discharge: 0.0
        nuclear: 0.07403926117601445
        oil: 0.0003404449242915256
        solar: 0.03256616055120062
        unknown: 0.03918342259842639
        wind: 8.579058326576934e-07
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Eastern
