bounding_box:
  - - -86.49625
    - 25.7531500000001
  - - -79.99125
    - 31.214009
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 47.6
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 50.1
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 257.2
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 184.2
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1478.4
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 10751.1
    - datetime: '2024-01-01'
      source: EIA.gov
      value: 10774.1
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1329.7
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1261.0
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 1414.8
    - datetime: '2024-05-01'
      source: EIA.gov
      value: 1414.6
    - datetime: '2024-06-01'
      source: EIA.gov
      value: 1489.5
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 18.8
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
comment: Duke Energy Florida Inc
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 35
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 405.89069477857464
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 428.05568940084476
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 426.5257292522346
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 443.4701743577631
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 432.2658778564117
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 437.88096646791024
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 437.0786046556874
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 0.0
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 0.0
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 521.6312947
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 569.16
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 423.934686
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 423.81
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 405.89069477857464
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 428.05568940084476
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 426.5257292522346
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 443.4701743577631
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 432.2658778564117
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 437.88096646791024
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 437.0786046556874
    oil:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 1162.940076
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 654.9
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 518.1245926495762
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 539.9600938015636
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 532.71
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 561.04
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 545.59
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 548.2
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 547.49
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 534.84
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 520.83
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 572.1600047
      - datetime: '2021-01-01'
        source: eGrid 2021; eGrid 2021
        value: 277.252
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 581.6312947
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 629.16
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 543.934686
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 543.81
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 518.1245926495762
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 539.9600938015636
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 532.71
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 561.04
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 545.59
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 548.2
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 547.49
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 534.84
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 520.83
    oil:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 1406.940076
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 898.9
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.103574549421613
        gas: 0.8561187845041084
        geothermal: 0.0
        hydro: 0.0049927946629394785
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0008967128878118871
        solar: 0.016946231230295997
        unknown: 0.017470979264185026
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.10357461431573237
        gas: 0.8561193209010795
        geothermal: 0.0
        hydro: 0.00499279779115017
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0008967134496428919
        solar: 0.01694561538424483
        unknown: 0.017470990210540285
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.10157920847507172
        gas: 0.8403458181977711
        geothermal: 0.0
        hydro: 0.006863864327474488
        hydro discharge: 9.009622117996716e-05
        nuclear: 0.008514612138142447
        oil: 0.0007975689699604503
        solar: 0.024686645609703115
        unknown: 0.017113436034960166
        wind: 8.864534196259375e-06
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.11044643417383712
        gas: 0.8323821242778364
        geothermal: 0.0
        hydro: 0.0048140955750781995
        hydro discharge: 4.6473488288236315e-05
        nuclear: 0.025083576877062395
        oil: 0.0006268895835372746
        solar: 0.002113550307257487
        unknown: 0.024481260190996158
        wind: 5.539710810572995e-06
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.054520413796950606
        gas: 0.8804188681775743
        geothermal: 0.0
        hydro: 0.005162940645953656
        hydro discharge: 8.818316689732797e-06
        nuclear: 0.02693672266583638
        oil: 0.000544747197975026
        solar: 0.006346303558091856
        unknown: 0.026055856140266564
        wind: 5.179919891963772e-06
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 6.5520892994865e-09
        coal: 0.11495082638143478
        gas: 0.8068263120365126
        geothermal: 0.0
        hydro: 0.005745241726830223
        hydro discharge: 9.764797086001381e-06
        nuclear: 0.028964982966445174
        oil: 0.0004028484764871474
        solar: 0.01645936284132258
        unknown: 0.026636697851870166
        wind: 4.523307648892722e-06
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.15012911931067283
        gas: 0.7695291200639496
        geothermal: 0.0
        hydro: 0.0058860549945065
        hydro discharge: 1.1004507994890575e-05
        nuclear: 0.02759918431909367
        oil: 0.0007122131611867743
        solar: 0.02290480132832567
        unknown: 0.02321706498105967
        wind: 1.1342287132759854e-05
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.2532114948225095e-07
        coal: 0.11669562136901877
        gas: 0.7924244325872296
        geothermal: 2.3486247633569724e-08
        hydro: 0.004461082095744108
        hydro discharge: 2.3137623645258927e-07
        nuclear: 0.026564264055729488
        oil: 0.0010955437273006152
        solar: 0.03301533701438382
        unknown: 0.025735660798846902
        wind: 7.552296504669766e-06
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.09719773229941774
        gas: 0.7893527032617939
        geothermal: 0.0
        hydro: 0.004110034609847192
        hydro discharge: 7.553860620192212e-08
        nuclear: 0.02933397649825593
        oil: 0.00045260795948853214
        solar: 0.04667329516351363
        unknown: 0.03287625554850145
        wind: 3.1488505704171863e-06
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Eastern
