bounding_box:
  - - -84.94623
    - 29.865082
  - - -83.591841
    - 31.123546
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 961.8
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 62.0
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
comment: City Of Tallahassee
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 35
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 357.04201641394957
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 347.26619391889955
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 358.5294426960453
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 372.35382463182555
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 365.40575243652324
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 349.73506836463935
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 355.877712517318
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 359.8683566
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 364.27
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 357.04201641394957
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 347.26619391889955
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 358.5294426960453
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 372.35382463182555
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 365.40575243652324
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 349.73506836463935
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 355.877712517318
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 474.2669761104115
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 463.9668381529327
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 464.07
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 482.33
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 476.58
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 459.45
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 467.76
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 465.68
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 464.11
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 479.8683566
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 484.27
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 474.2669761104115
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 463.9668381529327
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 464.07
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 482.33
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 476.58
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 459.45
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 467.76
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 465.68
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 464.11
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.9649769838658395
        geothermal: 0.0
        hydro: 0.007114899687620109
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.02790527891856134
        unknown: 0.0
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.9649777493327778
        geothermal: 0.0
        hydro: 0.007114905331506515
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.02790450549985011
        unknown: 0.0
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0507577460515821
        gas: 0.8474591811448173
        geothermal: 0.0
        hydro: 0.017497120577026324
        hydro discharge: 0.0005561930951260205
        nuclear: 0.05342082859760939
        oil: 3.03169766288876e-05
        solar: 0.027705843870457693
        unknown: 0.002514845685899153
        wind: 5.628571144483951e-05
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.06809312829494943
        gas: 0.8556091053617063
        geothermal: 0.0
        hydro: 0.017655282351135622
        hydro discharge: 0.00039378310573118366
        nuclear: 0.04642627610793376
        oil: 2.809980060571199e-05
        solar: 0.010298236684340652
        unknown: 0.0014524819042100454
        wind: 4.2051017260356286e-05
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.050640096891636156
        gas: 0.877900179407326
        geothermal: 0.0
        hydro: 0.013313194533216402
        hydro discharge: 5.8742120826674615e-05
        nuclear: 0.04285463430852859
        oil: 1.4003496436528795e-05
        solar: 0.01336087758984183
        unknown: 0.0018176217417546078
        wind: 3.809271987804134e-05
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.03356389181806555
        gas: 0.8744472736197433
        geothermal: 0.0
        hydro: 0.012635666773785708
        hydro discharge: 6.700134664514143e-05
        nuclear: 0.04234287060398591
        oil: 6.2976279037006925e-06
        solar: 0.034612742510590544
        unknown: 0.002289825342200384
        wind: 3.126017108760027e-05
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.04642927551324497
        gas: 0.8612996275082788
        geothermal: 0.0
        hydro: 0.011392297422831776
        hydro discharge: 7.993089418025805e-05
        nuclear: 0.04577902147876702
        oil: 4.995908303796344e-06
        solar: 0.03240237329295854
        unknown: 0.0025325689193373673
        wind: 7.673249403529303e-05
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.038909997976321525
        gas: 0.8720154832931706
        geothermal: 0.0
        hydro: 0.009224166883147639
        hydro discharge: 3.48043992760685e-06
        nuclear: 0.040831721088308445
        oil: 4.005376382667553e-05
        solar: 0.03665484871926986
        unknown: 0.0022029031892311602
        wind: 0.00011356280794717194
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.030797538680920625
        gas: 0.8863998956840717
        geothermal: 0.0
        hydro: 0.0072867703639253574
        hydro discharge: 7.111005792823849e-07
        nuclear: 0.03961448198273814
        oil: 4.746686607900183e-06
        solar: 0.03398329093399138
        unknown: 0.0018550303939006657
        wind: 5.477640249040707e-05
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Eastern
