bounding_box:
  - - -83.214478374
    - 26.985591
  - - -81.1327000919999
    - 28.9295718550001
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 12.6
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 69.1
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 486.0
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 6220.0
    - datetime: '2024-05-01'
      source: EIA.gov
      value: 6324.9
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1029.4
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 1258.9
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 325.3
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
comment: Tampa Electric Company
contributors:
  - brandongalbraith
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 35
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 438.9785393460564
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 515.6219766852632
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 515.6209248642195
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 562.8683442712703
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 524.5646752535644
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 505.2044030859081
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 510.62387145096113
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 0.0
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 0.0
    coal:
      datetime: '2021-01-01'
      source: eGrid 2021
      value: 863.2
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 432.8237021
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 360.34
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 438.9785393460564
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 515.6219766852632
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 515.6209248642195
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 562.8683442712703
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 524.5646752535644
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 505.2044030859081
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 510.62387145096113
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 547.2942101050799
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 595.4541895887378
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 584.16
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 634.77
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 603.63
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 589.57
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 565.53
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 541.08
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 512.77
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 1248.927719
      - datetime: '2021-01-01'
        source: eGrid 2021; eGrid 2021
        value: 277.252
    coal:
      - datetime: '2012-01-01'
        source: IPCC 2014; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 866.085401
      - datetime: '2021-01-01'
        source: eGrid 2021; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 969.2854010000001
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 552.8237021
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 480.34
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 547.2942101050799
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 595.4541895887378
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 584.16
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 634.77
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 603.63
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 589.57
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 565.53
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 541.08
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 512.77
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.1496933178035911
        gas: 0.6708066234639555
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.00032186813284632737
        solar: 0.045471096710197646
        unknown: 0.13370757381207277
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.14969362330281363
        gas: 0.6708079924689648
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0003218687897257779
        solar: 0.04546914867509421
        unknown: 0.13370784668704438
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.12637546812542227
        gas: 0.6826018670199077
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 9.289087798545193e-05
        solar: 0.05391037309356741
        unknown: 0.13701950919783484
        wind: 0.0
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.22179896217552159
        gas: 0.652828955803474
        geothermal: 0.0
        hydro: 0.00012102815228931162
        hydro discharge: 1.0750392509063563e-06
        nuclear: 0.0031222061947380544
        oil: 1.8563987000170638e-05
        solar: 0.007509782433565046
        unknown: 0.11459891873684676
        wind: 7.391705343988216e-08
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.16594888326269946
        gas: 0.6834176262211342
        geothermal: 0.0
        hydro: 0.0002253040937309146
        hydro discharge: 2.8593539440900616e-07
        nuclear: 0.003421931368408945
        oil: 5.469767706326956e-05
        solar: 0.03112931292485671
        unknown: 0.11580151940164207
        wind: 7.287639110749019e-08
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.14933344582787367
        gas: 0.6777454546540683
        geothermal: 0.0
        hydro: 0.0005091257558816756
        hydro discharge: 5.811639858323835e-07
        nuclear: 0.0044866111589784196
        oil: 0.00011783523435042269
        solar: 0.04714164291837433
        unknown: 0.1206649479017331
        wind: 1.37391013199145e-07
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.15971096499809245
        gas: 0.6530116791102059
        geothermal: 0.0
        hydro: 0.0004529745705680379
        hydro discharge: 7.055257095600735e-07
        nuclear: 0.0032101373912050337
        oil: 0.0001242839961097661
        solar: 0.051295099461450215
        unknown: 0.13219322739595377
        wind: 4.807483378536781e-07
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 2.2532972949977163e-09
        coal: 0.12370540454257524
        gas: 0.6964628572783125
        geothermal: 4.5065945899954324e-10
        hydro: 0.0004793542987324212
        hydro discharge: 1.8026378359981733e-08
        nuclear: 0.0037997140475600757
        oil: 0.00031461753613297406
        solar: 0.060027642099236646
        unknown: 0.11520937007541877
        wind: 6.98522161449292e-07
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.06622995531977967
        gas: 0.7200197828833081
        geothermal: 0.0
        hydro: 0.0005449365023865022
        hydro discharge: 1.3468102886542575e-09
        nuclear: 0.0041326092557388465
        oil: 0.00016720425265261165
        solar: 0.06986276641995624
        unknown: 0.13904232471243105
        wind: 1.8720663012294177e-07
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Eastern
