bounding_box:
  - - -86.0998
    - 29.463185332
  - - -80.848769105
    - 31.50107
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 5.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 148.5
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 595.0
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 2179.5
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 248.4
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 38.1
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 38
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 534.0811805662851
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 768.6259762575984
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 768.6257927159432
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 656.2950321809269
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 618.1744474912118
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 691.8993136186612
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 629.3057674336989
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 0.0
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 0.0
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 612.0220147
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 524.92
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 534.0811805662851
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 768.6259762575984
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 768.6257927159432
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 656.2950321809269
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 618.1744474912118
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 691.8993136186612
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 629.3057674336989
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 628.1729440979408
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 790.412195248952
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 788.81
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 688.19
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 647.78
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 716.15
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 638.46
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 630.01
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 627.16
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 82.16971627
      - datetime: '2021-01-01'
        source: eGrid 2021; eGrid 2021
        value: 277.252
    coal:
      datetime: '2012-01-01'
      source: IPCC 2014; Oberschelp, Christopher, et al. "Global emission hotspots
        of coal power generation."
      value: 880.658933
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 732.0220147
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 644.92
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 628.1729440979408
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 790.412195248952
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 788.81
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 688.19
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 647.78
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 716.15
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 638.46
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 630.01
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 627.16
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.4253744861572457
        gas: 0.5642683737322164
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0007695979123000611
        solar: 0.006620850616074635
        unknown: 0.0029656952304433957
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.425374587629121
        gas: 0.564268508336834
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0007695980958854568
        solar: 0.006620613331950827
        unknown: 0.002965695937901568
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.4143147130483686
        gas: 0.5758327266164772
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0002655909756065884
        solar: 0.006624491734495951
        unknown: 0.002961339378013461
        wind: 0.0
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.35155849259264665
        gas: 0.562603312340934
        geothermal: 0.0
        hydro: 0.0006605373843505893
        hydro discharge: 1.2512928425335953e-05
        nuclear: 0.06030699391355397
        oil: 0.00021352073154779183
        solar: 0.00780451834893812
        unknown: 0.01683824022892824
        wind: 1.239998437267909e-06
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.3102757587249222
        gas: 0.5672466592202967
        geothermal: 0.0
        hydro: 0.0005783282265411459
        hydro discharge: 3.5143431164062117e-06
        nuclear: 0.0792153420506989
        oil: 0.00014906042896184108
        solar: 0.01054328994153565
        unknown: 0.03198574557103387
        wind: 1.5530003191695732e-06
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.9016174547071782e-08
        coal: 0.3697090368452198
        gas: 0.5561513566484934
        geothermal: 0.0
        hydro: 0.00036803821539382957
        hydro discharge: 1.9570123979529964e-06
        nuclear: 0.040461283415460646
        oil: 0.0001680145164449608
        solar: 0.010888132399926776
        unknown: 0.022251187971635285
        wind: 4.944205382238663e-07
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.276315439646765
        gas: 0.6186530101731034
        geothermal: 0.0
        hydro: 0.00030210587420680525
        hydro discharge: 2.7069454648544344e-06
        nuclear: 0.05845683421369193
        oil: 0.00022476078959413417
        solar: 0.01657684338788424
        unknown: 0.029465882713311117
        wind: 1.7168345902873863e-06
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 5.701845829082726e-07
        coal: 0.2758421087049864
        gas: 0.6049238700126057
        geothermal: 1.261752998592536e-07
        hydro: 0.0002331008807114989
        hydro discharge: 1.4294543465067337e-07
        nuclear: 0.06268039199768426
        oil: 0.00025417774583292473
        solar: 0.020211253851142665
        unknown: 0.03584900285948447
        wind: 4.6892491188198555e-06
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.2707978566250563
        gas: 0.6020545320476087
        geothermal: 0.0
        hydro: 0.0002976269014531413
        hydro discharge: 0.0
        nuclear: 0.056366675062774936
        oil: 0.000151928534228544
        solar: 0.025494787812400485
        unknown: 0.04483431517257192
        wind: 1.722391060397682e-06
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Eastern
