bounding_box:
  - - -83.67149
    - 24.02126
  - - -79.53074
    - 31.33017
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 493.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 617.6
    - datetime: '2024-04-01'
      source: EIA.gov
      value: 540.6
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 25465.8
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 43.5
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 3797.2
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 274.5
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 4584.8
    - datetime: '2024-01-01'
      source: EIA.gov
      value: 5478.8
    - datetime: '2024-03-01'
      source: EIA.gov
      value: 6223.8
    - datetime: '2024-05-01'
      source: EIA.gov
      value: 6223.4
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
comment: Florida Power & Light Company
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 35
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 295.8950245077242
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 294.2582526482979
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 297.5372931648557
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 313.1537940627542
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 318.3385132851559
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 317.11495667736415
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 311.44269883203356
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 0.0
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 0.0
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 367.4893706
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 365.66
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 295.8950245077242
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 294.2582526482979
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 297.5372931648557
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 313.1537940627542
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 318.3385132851559
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 317.11495667736415
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 311.44269883203356
    oil:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 390.0504417
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 450.53
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 390.1357904799577
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 387.86446506356134
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 388.63
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 408.2
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 413.14
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 417.35
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 401.62
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 401.8
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 407.43
    biomass:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 902.3445824
      - datetime: '2021-01-01'
        source: eGrid 2021; eGrid 2021
        value: 277.252
    coal:
      datetime: '2014-01-01'
      source: IPCC 2014
      value: 820.0
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 487.4893706
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 485.66
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 390.1357904799577
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 387.86446506356134
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 388.63
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 408.2
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 413.14
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 417.35
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 401.62
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 401.8
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 407.43
    oil:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 634.0504417
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 694.53
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.6519385220184877
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.2202698523204888
        oil: 4.593666138456435e-05
        solar: 0.03268655720609928
        unknown: 0.09505922335091438
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.0
        gas: 0.6519390424823136
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.22027002816910976
        oil: 4.593669805730223e-05
        solar: 0.03268578494253772
        unknown: 0.09505929923979868
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.006595026716729716
        gas: 0.6309368124547509
        geothermal: 0.0
        hydro: 0.0017167608525000134
        hydro discharge: 7.978041203546588e-05
        nuclear: 0.21807524854111948
        oil: 3.8732217004218e-06
        solar: 0.04193130763892869
        unknown: 0.10065611552155847
        wind: 5.006485734999835e-06
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.028580947356658972
        gas: 0.7179308722387208
        geothermal: 0.0
        hydro: 0.0014786649239248916
        hydro discharge: 3.409749345694072e-05
        nuclear: 0.20285057615766006
        oil: 3.99733688428881e-06
        solar: 0.012703288139892206
        unknown: 0.036413544677263834
        wind: 3.970583054748293e-06
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.02855143736043348
        gas: 0.6595545403741645
        geothermal: 0.0
        hydro: 0.001517425493089117
        hydro discharge: 9.27291910139317e-06
        nuclear: 0.21017064466712487
        oil: 3.0470330487412616e-06
        solar: 0.017432253569675045
        unknown: 0.0827561132554723
        wind: 5.19428207055004e-06
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.6544105136847472e-07
        coal: 0.03132784396805341
        gas: 0.6450581559271549
        geothermal: 2.9315155552714635e-08
        hydro: 0.001121948801022012
        hydro discharge: 6.6699839413094505e-06
        nuclear: 0.20324344808252404
        oil: 3.1357043989951036e-06
        solar: 0.024792772534054968
        unknown: 0.09444306315089453
        wind: 3.004294821580569e-06
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.030820494571289637
        gas: 0.6161186719811114
        geothermal: 0.0
        hydro: 0.0010515976781821032
        hydro discharge: 8.80825034441512e-06
        nuclear: 0.21464563814979826
        oil: 3.0053829567318217e-06
        solar: 0.04222998753788053
        unknown: 0.0951149807081493
        wind: 6.756818841058031e-06
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.6114529802284065e-06
        coal: 0.025082416313666533
        gas: 0.6036497472567969
        geothermal: 2.8362618614181956e-07
        hydro: 0.0007875567602146431
        hydro discharge: 6.325648572584075e-07
        nuclear: 0.20747789029916658
        oil: 1.0811214142452985e-05
        solar: 0.05072565451687748
        unknown: 0.11224778580265168
        wind: 1.557604688945539e-05
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.015793602435529863
        gas: 0.5976112639443812
        geothermal: 0.0
        hydro: 0.0009078164939836041
        hydro discharge: 2.0544486134627162e-07
        nuclear: 0.18561807466060484
        oil: 2.9464907357451616e-06
        solar: 0.06230846639729622
        unknown: 0.13775105878006305
        wind: 6.526480987052543e-06
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Eastern
