bounding_box:
  - - -85.65399
    - 25.7184577510001
  - - -80.123257233
    - 31.2115600000001
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1.6
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 1429.2
    - datetime: '2024-01-01'
      source: EIA.gov
      value: 714.6
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 2036.5
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 74.5
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
comment: Seminole Electric Cooperative
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 35
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 375.6156090155082
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 394.6535931946128
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 394.65359249008145
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 387.0179431883102
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 721.2152218900337
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 704.620342180618
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 699.4161197629264
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 964.3118179
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 940.15
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 386.3298038
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 387.4
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 375.6156090155082
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 394.6535931946128
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 394.65359249008145
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 387.0179431883102
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 721.2152218900337
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 704.620342180618
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 699.4161197629264
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 494.74568708750655
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 514.3329608680659
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 770.39
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 874.09
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 823.0
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 811.14
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 792.91
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 780.32
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 662.44
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 1062.1123579
      - datetime: '2021-01-01'
        source: eGrid 2021; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 1037.95054
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 506.3298038
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 507.4
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 494.74568708750655
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 514.3329608680659
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 770.39
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 874.09
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 823.0
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 811.14
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 792.91
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 780.32
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 662.44
    oil:
      datetime: '2014-01-01'
      source: IPCC 2014; EIA 2020/BEIS 2021
      value: 650.0
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.6
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.014416969634279101
        gas: 0.9855614963288232
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 2.151871963618696e-05
        unknown: 0.0
        wind: 0.0
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.014416969686159187
        gas: 0.9855614998754085
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 2.1515138889387014e-05
        unknown: 0.0
        wind: 0.0
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.4754266094797515
        gas: 0.5242182323973947
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0003560444701491057
        unknown: 0.0
        wind: 0.0
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.662193538523946
        gas: 0.33311796667785654
        geothermal: 0.0
        hydro: 1.8473418466736775e-05
        hydro discharge: 2.1707894790525003e-07
        nuclear: 0.00130061667570442
        oil: 6.614987576167256e-06
        solar: 0.0006306222374446751
        unknown: 0.0027309715713469025
        wind: 0.0
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.5482004778989513
        gas: 0.4471363888269975
        geothermal: 0.0
        hydro: 2.1924918004146562e-05
        hydro discharge: 0.0
        nuclear: 0.0011810030841925055
        oil: 6.5022221153832266e-06
        solar: 0.0011643036190717227
        unknown: 0.0022842923537393835
        wind: 0.0
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.5439558639674121
        gas: 0.44756428195919606
        geothermal: 0.0
        hydro: 1.8004805251615875e-05
        hydro discharge: 0.0
        nuclear: 0.001583889440558038
        oil: 7.3875235833537545e-06
        solar: 0.004354335005780499
        unknown: 0.0025119187755300223
        wind: 4.384286993088281e-08
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.5732979826044147
        gas: 0.4185457875639141
        geothermal: 0.0
        hydro: 3.808786164113348e-05
        hydro discharge: 0.0
        nuclear: 0.002625029471799897
        oil: 1.6920843813747482e-06
        solar: 0.0015752667068190838
        unknown: 0.003911875606895595
        wind: 0.0
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.5164563586961312
        gas: 0.4789388785614026
        geothermal: 0.0
        hydro: 2.3163801250966236e-05
        hydro discharge: 0.0
        nuclear: 0.0014510516913121463
        oil: 1.0537180197893144e-05
        solar: 0.0013034361939573162
        unknown: 0.0018145194255291314
        wind: 4.998662332966386e-09
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.29472288670756824
        gas: 0.6977120445265669
        geothermal: 0.0
        hydro: 2.825457464246402e-05
        hydro discharge: 0.0
        nuclear: 0.0007557779393918895
        oil: 2.0392623631271766e-05
        solar: 0.0021897581637442235
        unknown: 0.004569934102315827
        wind: 0.0
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Eastern
