bounding_box:
  - - -98.45079
    - 34.168033532
  - - -88.5987499999999
    - 41.779649115
capacity:
  battery storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  biomass:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 4.0
  coal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 2481.7
  gas:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 3044.6
  geothermal:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  hydro:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 30.0
  hydro storage:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 31.0
  nuclear:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  oil:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 44.3
    - datetime: '2023-12-01'
      source: EIA.gov
      value: 97.5
  solar:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 4.0
    - datetime: '2024-02-01'
      source: EIA.gov
      value: 1.5
  unknown:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 0.0
  wind:
    - datetime: '2023-10-01'
      source: EIA.gov
      value: 941.4
comment: Associated Electric Cooperative, Inc.
contributors:
  - systemcatch
  - robertahunt
  - KabelWlan
country: US
delays:
  consumption: 30
  consumptionForecast: 30
  production: 34
disclaimer: Data for real-time consumption and generation mix is estimated. Real-time
  exchanges are not available.
emissionFactors:
  direct:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 573.938558639881
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 699.0356108885563
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 677.0140336927291
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 690.0484201394944
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 650.1103234801468
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 606.4947815521948
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 617.5607015534879
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 950.6306844
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 933.86
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020
        value: 400.7407839
      - datetime: '2021-01-01'
        source: eGrid 2021
        value: 408.74
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 573.938558639881
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 699.0356108885563
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 677.0140336927291
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 690.0484201394944
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 650.1103234801468
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 606.4947815521948
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 617.5607015534879
    oil:
      datetime: '2021-01-01'
      source: eGrid 2021
      value: 664.14
  lifecycle:
    battery discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 647.8231721987329
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 759.4518396337845
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 718.57
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 749.71
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 711.78
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 668.96
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 663.25
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 663.85
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 619.21
    coal:
      - datetime: '2020-01-01'
        source: eGrid 2020; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 988.4513953999999
      - datetime: '2021-01-01'
        source: eGrid 2021; Oberschelp, Christopher, et al. "Global emission hotspots
          of coal power generation."
        value: 971.680711
    gas:
      - datetime: '2020-01-01'
        source: eGrid 2020; IPCC 2014
        value: 520.7407839
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 528.74
    hydro discharge:
      - datetime: '2015-01-01'
        source: Electricity Maps, 2015 average
        value: 647.8231721987329
      - datetime: '2016-01-01'
        source: Electricity Maps, 2016 average
        value: 759.4518396337845
      - datetime: '2017-01-01'
        source: Electricity Maps, 2017 average
        value: 718.57
      - datetime: '2018-01-01'
        source: Electricity Maps, 2018 average
        value: 749.71
      - datetime: '2019-01-01'
        source: Electricity Maps, 2019 average
        value: 711.78
      - datetime: '2020-01-01'
        source: Electricity Maps, 2020 average
        value: 668.96
      - datetime: '2021-01-01'
        source: Electricity Maps, 2021 average
        value: 663.25
      - datetime: '2022-01-01'
        source: Electricity Maps, 2022 average
        value: 663.85
      - datetime: '2023-01-01'
        source: Electricity Maps, 2023 average
        value: 619.21
    oil:
      - datetime: '2014-01-01'
        source: IPCC 2014; EIA 2020/BEIS 2021
        value: 650.0
      - datetime: '2021-01-01'
        source: eGrid 2021; IPCC 2014
        value: 908.14
    solar:
      datetime: '2021-01-01'
      source: INCER ACV
      value: 25.66
fallbackZoneMixes:
  powerOriginRatios:
    - _source: Electricity Maps, 2015 average
      datetime: '2015-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.6072063967814186
        gas: 0.3039511770625133
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 0.0
        wind: 0.08884258146902137
    - _source: Electricity Maps, 2016 average
      datetime: '2016-01-01'
      value:
        battery discharge: 0.0
        biomass: 0.0
        coal: 0.6072063967814186
        gas: 0.3039511770625133
        geothermal: 0.0
        hydro: 0.0
        hydro discharge: 0.0
        nuclear: 0.0
        oil: 0.0
        solar: 0.0
        unknown: 0.0
        wind: 0.08884258146902135
    - _source: Electricity Maps, 2017 average
      datetime: '2017-01-01'
      value:
        battery discharge: 0.0
        biomass: 4.686594876800686e-05
        coal: 0.5590957985495583
        gas: 0.3067803314063547
        geothermal: 0.0
        hydro: 0.004521995994014524
        hydro discharge: 1.0733731505507111e-08
        nuclear: 0.008423174425213528
        oil: 0.000774888306338088
        solar: 0.00014709175386485237
        unknown: 0.0002420803236586647
        wind: 0.11996767668864579
    - _source: Electricity Maps, 2018 average
      datetime: '2018-01-01'
      value:
        battery discharge: 0.0
        biomass: 3.122672299882581e-05
        coal: 0.5922622384488977
        gas: 0.27926343698805567
        geothermal: 0.0
        hydro: 0.03752157609161176
        hydro discharge: 3.772140098447039e-07
        nuclear: 0.005941923714924819
        oil: 0.0003801391099636453
        solar: 0.00011177502355616916
        unknown: 0.019824176963940978
        wind: 0.06466302104042573
    - _source: Electricity Maps, 2019 average
      datetime: '2019-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.20273318208189e-05
        coal: 0.5439894779553347
        gas: 0.2969636811045961
        geothermal: 0.0
        hydro: 0.07532403645495904
        hydro discharge: 5.003499857997519e-08
        nuclear: 0.0037942742967755623
        oil: 5.8031583037711776e-06
        solar: 5.0491624287736586e-05
        unknown: 0.02211478195457575
        wind: 0.057745257983720724
    - _source: Electricity Maps, 2020 average
      datetime: '2020-01-01'
      value:
        battery discharge: 0.0
        biomass: 1.4413228927688788e-05
        coal: 0.497883212958416
        gas: 0.29614415194966726
        geothermal: 0.0
        hydro: 0.08080374337848631
        hydro discharge: 7.36896190583226e-08
        nuclear: 0.005918688027148391
        oil: 1.0594724980110332e-05
        solar: 8.191844670654167e-05
        unknown: 0.0259850354244214
        wind: 0.09315791210020101
    - _source: Electricity Maps, 2021 average
      datetime: '2021-01-01'
      value:
        battery discharge: 0.0
        biomass: 2.803587669030899e-05
        coal: 0.5415517739072656
        gas: 0.2218578694075607
        geothermal: 0.0
        hydro: 0.07097586903069114
        hydro discharge: 2.4915763331017153e-07
        nuclear: 0.010041685500151424
        oil: 2.422689022289304e-05
        solar: 0.0002301122669005599
        unknown: 0.018638544951265032
        wind: 0.1366514962787715
    - _source: Electricity Maps, 2022 average
      datetime: '2022-01-01'
      value:
        battery discharge: 0.0
        biomass: 2.4490892671772802e-05
        coal: 0.5270579732309603
        gas: 0.2566115755161757
        geothermal: 0.0
        hydro: 0.044381435601967424
        hydro discharge: 2.3768719737094097e-09
        nuclear: 0.008784026695549178
        oil: 5.346020828734308e-05
        solar: 0.0003355572777603996
        unknown: 0.013560683292649226
        wind: 0.1491906035689128
    - _source: Electricity Maps, 2023 average
      datetime: '2023-01-01'
      value:
        battery discharge: 0.0
        biomass: 3.680957447909629e-05
        coal: 0.4183304350633703
        gas: 0.3778997594305698
        geothermal: 0.0
        hydro: 0.04788051295181173
        hydro discharge: 2.1496399401467156e-09
        nuclear: 0.012372106070070502
        oil: 4.252503715195837e-05
        solar: 0.0008954884077065582
        unknown: 0.008782734031810823
        wind: 0.1337594467136342
parsers:
  consumption: EIA.fetch_consumption
  consumptionForecast: EIA.fetch_consumption_forecast
  production: EIA.fetch_production_mix
  productionCapacity: EIA.fetch_production_capacity
region: Americas
sources:
  INCER ACV:
    link: https://docs.google.com/spreadsheets/d/1w5DJ7sPen6axIHU8TCVcuzNCjlct4I6JAbhUlw-ZXu8/edit?usp=sharing
  IPCC 2014:
    link: https://www.ipcc.ch/site/assets/uploads/2018/02/ipcc_wg3_ar5_annex-iii.pdf#page=7
  eGrid 2020:
    link: https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing
  eGrid 2021:
    link: ' https://drive.google.com/file/d/1_FAAuTtIdMuORZKsqHnd9vMNHlQgYarh/view?usp=sharing'
timezone: US/Central
